// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.1.0.proto

package com.jomofisher.cmakeserver.model;

public interface CapabilitiesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Capabilities)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Generator generators = 1;</code>
   */
  java.util.List<com.jomofisher.cmakeserver.model.Generator> 
      getGeneratorsList();
  /**
   * <code>repeated .Generator generators = 1;</code>
   */
  com.jomofisher.cmakeserver.model.Generator getGenerators(int index);
  /**
   * <code>repeated .Generator generators = 1;</code>
   */
  int getGeneratorsCount();
  /**
   * <code>repeated .Generator generators = 1;</code>
   */
  java.util.List<? extends com.jomofisher.cmakeserver.model.GeneratorOrBuilder> 
      getGeneratorsOrBuilderList();
  /**
   * <code>repeated .Generator generators = 1;</code>
   */
  com.jomofisher.cmakeserver.model.GeneratorOrBuilder getGeneratorsOrBuilder(
      int index);

  /**
   * <code>optional bool serverMode = 2;</code>
   */
  boolean getServerMode();

  /**
   * <code>optional .Version version = 3;</code>
   */
  boolean hasVersion();
  /**
   * <code>optional .Version version = 3;</code>
   */
  com.jomofisher.cmakeserver.model.Version getVersion();
  /**
   * <code>optional .Version version = 3;</code>
   */
  com.jomofisher.cmakeserver.model.VersionOrBuilder getVersionOrBuilder();
}
