// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.1.0.proto

package com.jomofisher.cmakeserver.model;

/**
 * Protobuf type {@code CodeModelReply}
 */
public  final class CodeModelReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CodeModelReply)
    CodeModelReplyOrBuilder {
  // Use CodeModelReply.newBuilder() to construct.
  private CodeModelReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CodeModelReply() {
    type_ = "";
    cookie_ = "";
    inReplyTo_ = "";
    configurations_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CodeModelReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            cookie_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            inReplyTo_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              configurations_ = new java.util.ArrayList<com.jomofisher.cmakeserver.model.Configuration>();
              mutable_bitField0_ |= 0x00000008;
            }
            configurations_.add(
                input.readMessage(com.jomofisher.cmakeserver.model.Configuration.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        configurations_ = java.util.Collections.unmodifiableList(configurations_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jomofisher.cmakeserver.model.Messages10.internal_static_CodeModelReply_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jomofisher.cmakeserver.model.Messages10.internal_static_CodeModelReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jomofisher.cmakeserver.model.CodeModelReply.class, com.jomofisher.cmakeserver.model.CodeModelReply.Builder.class);
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object type_;
  /**
   * <code>optional string type = 1;</code>
   */
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>optional string type = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COOKIE_FIELD_NUMBER = 2;
  private volatile java.lang.Object cookie_;
  /**
   * <code>optional string cookie = 2;</code>
   */
  public java.lang.String getCookie() {
    java.lang.Object ref = cookie_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cookie_ = s;
      return s;
    }
  }
  /**
   * <code>optional string cookie = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCookieBytes() {
    java.lang.Object ref = cookie_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cookie_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INREPLYTO_FIELD_NUMBER = 3;
  private volatile java.lang.Object inReplyTo_;
  /**
   * <code>optional string inReplyTo = 3;</code>
   */
  public java.lang.String getInReplyTo() {
    java.lang.Object ref = inReplyTo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      inReplyTo_ = s;
      return s;
    }
  }
  /**
   * <code>optional string inReplyTo = 3;</code>
   */
  public com.google.protobuf.ByteString
      getInReplyToBytes() {
    java.lang.Object ref = inReplyTo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      inReplyTo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONFIGURATIONS_FIELD_NUMBER = 4;
  private java.util.List<com.jomofisher.cmakeserver.model.Configuration> configurations_;
  /**
   * <code>repeated .Configuration configurations = 4;</code>
   */
  public java.util.List<com.jomofisher.cmakeserver.model.Configuration> getConfigurationsList() {
    return configurations_;
  }
  /**
   * <code>repeated .Configuration configurations = 4;</code>
   */
  public java.util.List<? extends com.jomofisher.cmakeserver.model.ConfigurationOrBuilder> 
      getConfigurationsOrBuilderList() {
    return configurations_;
  }
  /**
   * <code>repeated .Configuration configurations = 4;</code>
   */
  public int getConfigurationsCount() {
    return configurations_.size();
  }
  /**
   * <code>repeated .Configuration configurations = 4;</code>
   */
  public com.jomofisher.cmakeserver.model.Configuration getConfigurations(int index) {
    return configurations_.get(index);
  }
  /**
   * <code>repeated .Configuration configurations = 4;</code>
   */
  public com.jomofisher.cmakeserver.model.ConfigurationOrBuilder getConfigurationsOrBuilder(
      int index) {
    return configurations_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
    }
    if (!getCookieBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cookie_);
    }
    if (!getInReplyToBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, inReplyTo_);
    }
    for (int i = 0; i < configurations_.size(); i++) {
      output.writeMessage(4, configurations_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
    }
    if (!getCookieBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cookie_);
    }
    if (!getInReplyToBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, inReplyTo_);
    }
    for (int i = 0; i < configurations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, configurations_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.jomofisher.cmakeserver.model.CodeModelReply)) {
      return super.equals(obj);
    }
    com.jomofisher.cmakeserver.model.CodeModelReply other = (com.jomofisher.cmakeserver.model.CodeModelReply) obj;

    boolean result = true;
    result = result && getType()
        .equals(other.getType());
    result = result && getCookie()
        .equals(other.getCookie());
    result = result && getInReplyTo()
        .equals(other.getInReplyTo());
    result = result && getConfigurationsList()
        .equals(other.getConfigurationsList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + COOKIE_FIELD_NUMBER;
    hash = (53 * hash) + getCookie().hashCode();
    hash = (37 * hash) + INREPLYTO_FIELD_NUMBER;
    hash = (53 * hash) + getInReplyTo().hashCode();
    if (getConfigurationsCount() > 0) {
      hash = (37 * hash) + CONFIGURATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getConfigurationsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.jomofisher.cmakeserver.model.CodeModelReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jomofisher.cmakeserver.model.CodeModelReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.CodeModelReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jomofisher.cmakeserver.model.CodeModelReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.CodeModelReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jomofisher.cmakeserver.model.CodeModelReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.CodeModelReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.jomofisher.cmakeserver.model.CodeModelReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.CodeModelReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jomofisher.cmakeserver.model.CodeModelReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.jomofisher.cmakeserver.model.CodeModelReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CodeModelReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CodeModelReply)
      com.jomofisher.cmakeserver.model.CodeModelReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jomofisher.cmakeserver.model.Messages10.internal_static_CodeModelReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jomofisher.cmakeserver.model.Messages10.internal_static_CodeModelReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jomofisher.cmakeserver.model.CodeModelReply.class, com.jomofisher.cmakeserver.model.CodeModelReply.Builder.class);
    }

    // Construct using com.jomofisher.cmakeserver.model.CodeModelReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getConfigurationsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      type_ = "";

      cookie_ = "";

      inReplyTo_ = "";

      if (configurationsBuilder_ == null) {
        configurations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        configurationsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jomofisher.cmakeserver.model.Messages10.internal_static_CodeModelReply_descriptor;
    }

    public com.jomofisher.cmakeserver.model.CodeModelReply getDefaultInstanceForType() {
      return com.jomofisher.cmakeserver.model.CodeModelReply.getDefaultInstance();
    }

    public com.jomofisher.cmakeserver.model.CodeModelReply build() {
      com.jomofisher.cmakeserver.model.CodeModelReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.jomofisher.cmakeserver.model.CodeModelReply buildPartial() {
      com.jomofisher.cmakeserver.model.CodeModelReply result = new com.jomofisher.cmakeserver.model.CodeModelReply(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.type_ = type_;
      result.cookie_ = cookie_;
      result.inReplyTo_ = inReplyTo_;
      if (configurationsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          configurations_ = java.util.Collections.unmodifiableList(configurations_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.configurations_ = configurations_;
      } else {
        result.configurations_ = configurationsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jomofisher.cmakeserver.model.CodeModelReply) {
        return mergeFrom((com.jomofisher.cmakeserver.model.CodeModelReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jomofisher.cmakeserver.model.CodeModelReply other) {
      if (other == com.jomofisher.cmakeserver.model.CodeModelReply.getDefaultInstance()) return this;
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (!other.getCookie().isEmpty()) {
        cookie_ = other.cookie_;
        onChanged();
      }
      if (!other.getInReplyTo().isEmpty()) {
        inReplyTo_ = other.inReplyTo_;
        onChanged();
      }
      if (configurationsBuilder_ == null) {
        if (!other.configurations_.isEmpty()) {
          if (configurations_.isEmpty()) {
            configurations_ = other.configurations_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureConfigurationsIsMutable();
            configurations_.addAll(other.configurations_);
          }
          onChanged();
        }
      } else {
        if (!other.configurations_.isEmpty()) {
          if (configurationsBuilder_.isEmpty()) {
            configurationsBuilder_.dispose();
            configurationsBuilder_ = null;
            configurations_ = other.configurations_;
            bitField0_ = (bitField0_ & ~0x00000008);
            configurationsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getConfigurationsFieldBuilder() : null;
          } else {
            configurationsBuilder_.addAllMessages(other.configurations_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.jomofisher.cmakeserver.model.CodeModelReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.jomofisher.cmakeserver.model.CodeModelReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object type_ = "";
    /**
     * <code>optional string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string type = 1;</code>
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string type = 1;</code>
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>optional string type = 1;</code>
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cookie_ = "";
    /**
     * <code>optional string cookie = 2;</code>
     */
    public java.lang.String getCookie() {
      java.lang.Object ref = cookie_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cookie_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string cookie = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCookieBytes() {
      java.lang.Object ref = cookie_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cookie_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string cookie = 2;</code>
     */
    public Builder setCookie(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cookie_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string cookie = 2;</code>
     */
    public Builder clearCookie() {
      
      cookie_ = getDefaultInstance().getCookie();
      onChanged();
      return this;
    }
    /**
     * <code>optional string cookie = 2;</code>
     */
    public Builder setCookieBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cookie_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object inReplyTo_ = "";
    /**
     * <code>optional string inReplyTo = 3;</code>
     */
    public java.lang.String getInReplyTo() {
      java.lang.Object ref = inReplyTo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        inReplyTo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string inReplyTo = 3;</code>
     */
    public com.google.protobuf.ByteString
        getInReplyToBytes() {
      java.lang.Object ref = inReplyTo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        inReplyTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string inReplyTo = 3;</code>
     */
    public Builder setInReplyTo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      inReplyTo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string inReplyTo = 3;</code>
     */
    public Builder clearInReplyTo() {
      
      inReplyTo_ = getDefaultInstance().getInReplyTo();
      onChanged();
      return this;
    }
    /**
     * <code>optional string inReplyTo = 3;</code>
     */
    public Builder setInReplyToBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      inReplyTo_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.jomofisher.cmakeserver.model.Configuration> configurations_ =
      java.util.Collections.emptyList();
    private void ensureConfigurationsIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        configurations_ = new java.util.ArrayList<com.jomofisher.cmakeserver.model.Configuration>(configurations_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.jomofisher.cmakeserver.model.Configuration, com.jomofisher.cmakeserver.model.Configuration.Builder, com.jomofisher.cmakeserver.model.ConfigurationOrBuilder> configurationsBuilder_;

    /**
     * <code>repeated .Configuration configurations = 4;</code>
     */
    public java.util.List<com.jomofisher.cmakeserver.model.Configuration> getConfigurationsList() {
      if (configurationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(configurations_);
      } else {
        return configurationsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Configuration configurations = 4;</code>
     */
    public int getConfigurationsCount() {
      if (configurationsBuilder_ == null) {
        return configurations_.size();
      } else {
        return configurationsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Configuration configurations = 4;</code>
     */
    public com.jomofisher.cmakeserver.model.Configuration getConfigurations(int index) {
      if (configurationsBuilder_ == null) {
        return configurations_.get(index);
      } else {
        return configurationsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Configuration configurations = 4;</code>
     */
    public Builder setConfigurations(
        int index, com.jomofisher.cmakeserver.model.Configuration value) {
      if (configurationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConfigurationsIsMutable();
        configurations_.set(index, value);
        onChanged();
      } else {
        configurationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Configuration configurations = 4;</code>
     */
    public Builder setConfigurations(
        int index, com.jomofisher.cmakeserver.model.Configuration.Builder builderForValue) {
      if (configurationsBuilder_ == null) {
        ensureConfigurationsIsMutable();
        configurations_.set(index, builderForValue.build());
        onChanged();
      } else {
        configurationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Configuration configurations = 4;</code>
     */
    public Builder addConfigurations(com.jomofisher.cmakeserver.model.Configuration value) {
      if (configurationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConfigurationsIsMutable();
        configurations_.add(value);
        onChanged();
      } else {
        configurationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Configuration configurations = 4;</code>
     */
    public Builder addConfigurations(
        int index, com.jomofisher.cmakeserver.model.Configuration value) {
      if (configurationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConfigurationsIsMutable();
        configurations_.add(index, value);
        onChanged();
      } else {
        configurationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Configuration configurations = 4;</code>
     */
    public Builder addConfigurations(
        com.jomofisher.cmakeserver.model.Configuration.Builder builderForValue) {
      if (configurationsBuilder_ == null) {
        ensureConfigurationsIsMutable();
        configurations_.add(builderForValue.build());
        onChanged();
      } else {
        configurationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Configuration configurations = 4;</code>
     */
    public Builder addConfigurations(
        int index, com.jomofisher.cmakeserver.model.Configuration.Builder builderForValue) {
      if (configurationsBuilder_ == null) {
        ensureConfigurationsIsMutable();
        configurations_.add(index, builderForValue.build());
        onChanged();
      } else {
        configurationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Configuration configurations = 4;</code>
     */
    public Builder addAllConfigurations(
        java.lang.Iterable<? extends com.jomofisher.cmakeserver.model.Configuration> values) {
      if (configurationsBuilder_ == null) {
        ensureConfigurationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, configurations_);
        onChanged();
      } else {
        configurationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Configuration configurations = 4;</code>
     */
    public Builder clearConfigurations() {
      if (configurationsBuilder_ == null) {
        configurations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        configurationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Configuration configurations = 4;</code>
     */
    public Builder removeConfigurations(int index) {
      if (configurationsBuilder_ == null) {
        ensureConfigurationsIsMutable();
        configurations_.remove(index);
        onChanged();
      } else {
        configurationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Configuration configurations = 4;</code>
     */
    public com.jomofisher.cmakeserver.model.Configuration.Builder getConfigurationsBuilder(
        int index) {
      return getConfigurationsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Configuration configurations = 4;</code>
     */
    public com.jomofisher.cmakeserver.model.ConfigurationOrBuilder getConfigurationsOrBuilder(
        int index) {
      if (configurationsBuilder_ == null) {
        return configurations_.get(index);  } else {
        return configurationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Configuration configurations = 4;</code>
     */
    public java.util.List<? extends com.jomofisher.cmakeserver.model.ConfigurationOrBuilder> 
         getConfigurationsOrBuilderList() {
      if (configurationsBuilder_ != null) {
        return configurationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(configurations_);
      }
    }
    /**
     * <code>repeated .Configuration configurations = 4;</code>
     */
    public com.jomofisher.cmakeserver.model.Configuration.Builder addConfigurationsBuilder() {
      return getConfigurationsFieldBuilder().addBuilder(
          com.jomofisher.cmakeserver.model.Configuration.getDefaultInstance());
    }
    /**
     * <code>repeated .Configuration configurations = 4;</code>
     */
    public com.jomofisher.cmakeserver.model.Configuration.Builder addConfigurationsBuilder(
        int index) {
      return getConfigurationsFieldBuilder().addBuilder(
          index, com.jomofisher.cmakeserver.model.Configuration.getDefaultInstance());
    }
    /**
     * <code>repeated .Configuration configurations = 4;</code>
     */
    public java.util.List<com.jomofisher.cmakeserver.model.Configuration.Builder> 
         getConfigurationsBuilderList() {
      return getConfigurationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.jomofisher.cmakeserver.model.Configuration, com.jomofisher.cmakeserver.model.Configuration.Builder, com.jomofisher.cmakeserver.model.ConfigurationOrBuilder> 
        getConfigurationsFieldBuilder() {
      if (configurationsBuilder_ == null) {
        configurationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.jomofisher.cmakeserver.model.Configuration, com.jomofisher.cmakeserver.model.Configuration.Builder, com.jomofisher.cmakeserver.model.ConfigurationOrBuilder>(
                configurations_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        configurations_ = null;
      }
      return configurationsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:CodeModelReply)
  }

  // @@protoc_insertion_point(class_scope:CodeModelReply)
  private static final com.jomofisher.cmakeserver.model.CodeModelReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.jomofisher.cmakeserver.model.CodeModelReply();
  }

  public static com.jomofisher.cmakeserver.model.CodeModelReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CodeModelReply>
      PARSER = new com.google.protobuf.AbstractParser<CodeModelReply>() {
    public CodeModelReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new CodeModelReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CodeModelReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CodeModelReply> getParserForType() {
    return PARSER;
  }

  public com.jomofisher.cmakeserver.model.CodeModelReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

