// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.1.0.proto

package com.jomofisher.cmakeserver.model;

public interface CodeModelReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CodeModelReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string type = 1;</code>
   */
  java.lang.String getType();
  /**
   * <code>optional string type = 1;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>optional string cookie = 2;</code>
   */
  java.lang.String getCookie();
  /**
   * <code>optional string cookie = 2;</code>
   */
  com.google.protobuf.ByteString
      getCookieBytes();

  /**
   * <code>optional string inReplyTo = 3;</code>
   */
  java.lang.String getInReplyTo();
  /**
   * <code>optional string inReplyTo = 3;</code>
   */
  com.google.protobuf.ByteString
      getInReplyToBytes();

  /**
   * <code>repeated .Configuration configurations = 4;</code>
   */
  java.util.List<com.jomofisher.cmakeserver.model.Configuration> 
      getConfigurationsList();
  /**
   * <code>repeated .Configuration configurations = 4;</code>
   */
  com.jomofisher.cmakeserver.model.Configuration getConfigurations(int index);
  /**
   * <code>repeated .Configuration configurations = 4;</code>
   */
  int getConfigurationsCount();
  /**
   * <code>repeated .Configuration configurations = 4;</code>
   */
  java.util.List<? extends com.jomofisher.cmakeserver.model.ConfigurationOrBuilder> 
      getConfigurationsOrBuilderList();
  /**
   * <code>repeated .Configuration configurations = 4;</code>
   */
  com.jomofisher.cmakeserver.model.ConfigurationOrBuilder getConfigurationsOrBuilder(
      int index);
}
