// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.1.0.proto

package com.jomofisher.cmakeserver.model;

public interface ConfigureMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ConfigureMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string type = 1;</code>
   */
  java.lang.String getType();
  /**
   * <code>optional string type = 1;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>repeated string cacheArguments = 2;</code>
   */
  java.util.List<java.lang.String>
      getCacheArgumentsList();
  /**
   * <code>repeated string cacheArguments = 2;</code>
   */
  int getCacheArgumentsCount();
  /**
   * <code>repeated string cacheArguments = 2;</code>
   */
  java.lang.String getCacheArguments(int index);
  /**
   * <code>repeated string cacheArguments = 2;</code>
   */
  com.google.protobuf.ByteString
      getCacheArgumentsBytes(int index);
}
