// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.1.0.proto

package com.jomofisher.cmakeserver.model;

public interface ConfigurationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Configuration)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .Project projects = 2;</code>
   */
  java.util.List<com.jomofisher.cmakeserver.model.Project> 
      getProjectsList();
  /**
   * <code>repeated .Project projects = 2;</code>
   */
  com.jomofisher.cmakeserver.model.Project getProjects(int index);
  /**
   * <code>repeated .Project projects = 2;</code>
   */
  int getProjectsCount();
  /**
   * <code>repeated .Project projects = 2;</code>
   */
  java.util.List<? extends com.jomofisher.cmakeserver.model.ProjectOrBuilder> 
      getProjectsOrBuilderList();
  /**
   * <code>repeated .Project projects = 2;</code>
   */
  com.jomofisher.cmakeserver.model.ProjectOrBuilder getProjectsOrBuilder(
      int index);
}
