// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.1.0.proto

package com.jomofisher.cmakeserver.model;

/**
 * Protobuf type {@code FileGroup}
 */
public  final class FileGroup extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FileGroup)
    FileGroupOrBuilder {
  // Use FileGroup.newBuilder() to construct.
  private FileGroup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FileGroup() {
    compileFlags_ = "";
    isGenerated_ = false;
    language_ = "";
    sources_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    defines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    includePath_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private FileGroup(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            compileFlags_ = s;
            break;
          }
          case 16: {

            isGenerated_ = input.readBool();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            language_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              sources_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000008;
            }
            sources_.add(s);
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              defines_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000010;
            }
            defines_.add(s);
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              includePath_ = new java.util.ArrayList<com.jomofisher.cmakeserver.model.IncludePath>();
              mutable_bitField0_ |= 0x00000020;
            }
            includePath_.add(
                input.readMessage(com.jomofisher.cmakeserver.model.IncludePath.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        sources_ = sources_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        defines_ = defines_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        includePath_ = java.util.Collections.unmodifiableList(includePath_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jomofisher.cmakeserver.model.Messages10.internal_static_FileGroup_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jomofisher.cmakeserver.model.Messages10.internal_static_FileGroup_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jomofisher.cmakeserver.model.FileGroup.class, com.jomofisher.cmakeserver.model.FileGroup.Builder.class);
  }

  private int bitField0_;
  public static final int COMPILEFLAGS_FIELD_NUMBER = 1;
  private volatile java.lang.Object compileFlags_;
  /**
   * <code>optional string compileFlags = 1;</code>
   */
  public java.lang.String getCompileFlags() {
    java.lang.Object ref = compileFlags_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      compileFlags_ = s;
      return s;
    }
  }
  /**
   * <code>optional string compileFlags = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCompileFlagsBytes() {
    java.lang.Object ref = compileFlags_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      compileFlags_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISGENERATED_FIELD_NUMBER = 2;
  private boolean isGenerated_;
  /**
   * <code>optional bool isGenerated = 2;</code>
   */
  public boolean getIsGenerated() {
    return isGenerated_;
  }

  public static final int LANGUAGE_FIELD_NUMBER = 3;
  private volatile java.lang.Object language_;
  /**
   * <code>optional string language = 3;</code>
   */
  public java.lang.String getLanguage() {
    java.lang.Object ref = language_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      language_ = s;
      return s;
    }
  }
  /**
   * <code>optional string language = 3;</code>
   */
  public com.google.protobuf.ByteString
      getLanguageBytes() {
    java.lang.Object ref = language_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      language_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCES_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList sources_;
  /**
   * <code>repeated string sources = 4;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getSourcesList() {
    return sources_;
  }
  /**
   * <code>repeated string sources = 4;</code>
   */
  public int getSourcesCount() {
    return sources_.size();
  }
  /**
   * <code>repeated string sources = 4;</code>
   */
  public java.lang.String getSources(int index) {
    return sources_.get(index);
  }
  /**
   * <code>repeated string sources = 4;</code>
   */
  public com.google.protobuf.ByteString
      getSourcesBytes(int index) {
    return sources_.getByteString(index);
  }

  public static final int DEFINES_FIELD_NUMBER = 5;
  private com.google.protobuf.LazyStringList defines_;
  /**
   * <code>repeated string defines = 5;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getDefinesList() {
    return defines_;
  }
  /**
   * <code>repeated string defines = 5;</code>
   */
  public int getDefinesCount() {
    return defines_.size();
  }
  /**
   * <code>repeated string defines = 5;</code>
   */
  public java.lang.String getDefines(int index) {
    return defines_.get(index);
  }
  /**
   * <code>repeated string defines = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDefinesBytes(int index) {
    return defines_.getByteString(index);
  }

  public static final int INCLUDEPATH_FIELD_NUMBER = 6;
  private java.util.List<com.jomofisher.cmakeserver.model.IncludePath> includePath_;
  /**
   * <code>repeated .IncludePath includePath = 6;</code>
   */
  public java.util.List<com.jomofisher.cmakeserver.model.IncludePath> getIncludePathList() {
    return includePath_;
  }
  /**
   * <code>repeated .IncludePath includePath = 6;</code>
   */
  public java.util.List<? extends com.jomofisher.cmakeserver.model.IncludePathOrBuilder> 
      getIncludePathOrBuilderList() {
    return includePath_;
  }
  /**
   * <code>repeated .IncludePath includePath = 6;</code>
   */
  public int getIncludePathCount() {
    return includePath_.size();
  }
  /**
   * <code>repeated .IncludePath includePath = 6;</code>
   */
  public com.jomofisher.cmakeserver.model.IncludePath getIncludePath(int index) {
    return includePath_.get(index);
  }
  /**
   * <code>repeated .IncludePath includePath = 6;</code>
   */
  public com.jomofisher.cmakeserver.model.IncludePathOrBuilder getIncludePathOrBuilder(
      int index) {
    return includePath_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCompileFlagsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, compileFlags_);
    }
    if (isGenerated_ != false) {
      output.writeBool(2, isGenerated_);
    }
    if (!getLanguageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, language_);
    }
    for (int i = 0; i < sources_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sources_.getRaw(i));
    }
    for (int i = 0; i < defines_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, defines_.getRaw(i));
    }
    for (int i = 0; i < includePath_.size(); i++) {
      output.writeMessage(6, includePath_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCompileFlagsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, compileFlags_);
    }
    if (isGenerated_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isGenerated_);
    }
    if (!getLanguageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, language_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < sources_.size(); i++) {
        dataSize += computeStringSizeNoTag(sources_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getSourcesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < defines_.size(); i++) {
        dataSize += computeStringSizeNoTag(defines_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getDefinesList().size();
    }
    for (int i = 0; i < includePath_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, includePath_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.jomofisher.cmakeserver.model.FileGroup)) {
      return super.equals(obj);
    }
    com.jomofisher.cmakeserver.model.FileGroup other = (com.jomofisher.cmakeserver.model.FileGroup) obj;

    boolean result = true;
    result = result && getCompileFlags()
        .equals(other.getCompileFlags());
    result = result && (getIsGenerated()
        == other.getIsGenerated());
    result = result && getLanguage()
        .equals(other.getLanguage());
    result = result && getSourcesList()
        .equals(other.getSourcesList());
    result = result && getDefinesList()
        .equals(other.getDefinesList());
    result = result && getIncludePathList()
        .equals(other.getIncludePathList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + COMPILEFLAGS_FIELD_NUMBER;
    hash = (53 * hash) + getCompileFlags().hashCode();
    hash = (37 * hash) + ISGENERATED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsGenerated());
    hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
    hash = (53 * hash) + getLanguage().hashCode();
    if (getSourcesCount() > 0) {
      hash = (37 * hash) + SOURCES_FIELD_NUMBER;
      hash = (53 * hash) + getSourcesList().hashCode();
    }
    if (getDefinesCount() > 0) {
      hash = (37 * hash) + DEFINES_FIELD_NUMBER;
      hash = (53 * hash) + getDefinesList().hashCode();
    }
    if (getIncludePathCount() > 0) {
      hash = (37 * hash) + INCLUDEPATH_FIELD_NUMBER;
      hash = (53 * hash) + getIncludePathList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.jomofisher.cmakeserver.model.FileGroup parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jomofisher.cmakeserver.model.FileGroup parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.FileGroup parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jomofisher.cmakeserver.model.FileGroup parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.FileGroup parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jomofisher.cmakeserver.model.FileGroup parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.FileGroup parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.jomofisher.cmakeserver.model.FileGroup parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.FileGroup parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jomofisher.cmakeserver.model.FileGroup parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.jomofisher.cmakeserver.model.FileGroup prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FileGroup}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FileGroup)
      com.jomofisher.cmakeserver.model.FileGroupOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jomofisher.cmakeserver.model.Messages10.internal_static_FileGroup_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jomofisher.cmakeserver.model.Messages10.internal_static_FileGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jomofisher.cmakeserver.model.FileGroup.class, com.jomofisher.cmakeserver.model.FileGroup.Builder.class);
    }

    // Construct using com.jomofisher.cmakeserver.model.FileGroup.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getIncludePathFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      compileFlags_ = "";

      isGenerated_ = false;

      language_ = "";

      sources_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      defines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      if (includePathBuilder_ == null) {
        includePath_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        includePathBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jomofisher.cmakeserver.model.Messages10.internal_static_FileGroup_descriptor;
    }

    public com.jomofisher.cmakeserver.model.FileGroup getDefaultInstanceForType() {
      return com.jomofisher.cmakeserver.model.FileGroup.getDefaultInstance();
    }

    public com.jomofisher.cmakeserver.model.FileGroup build() {
      com.jomofisher.cmakeserver.model.FileGroup result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.jomofisher.cmakeserver.model.FileGroup buildPartial() {
      com.jomofisher.cmakeserver.model.FileGroup result = new com.jomofisher.cmakeserver.model.FileGroup(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.compileFlags_ = compileFlags_;
      result.isGenerated_ = isGenerated_;
      result.language_ = language_;
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        sources_ = sources_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.sources_ = sources_;
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        defines_ = defines_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.defines_ = defines_;
      if (includePathBuilder_ == null) {
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          includePath_ = java.util.Collections.unmodifiableList(includePath_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.includePath_ = includePath_;
      } else {
        result.includePath_ = includePathBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jomofisher.cmakeserver.model.FileGroup) {
        return mergeFrom((com.jomofisher.cmakeserver.model.FileGroup)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jomofisher.cmakeserver.model.FileGroup other) {
      if (other == com.jomofisher.cmakeserver.model.FileGroup.getDefaultInstance()) return this;
      if (!other.getCompileFlags().isEmpty()) {
        compileFlags_ = other.compileFlags_;
        onChanged();
      }
      if (other.getIsGenerated() != false) {
        setIsGenerated(other.getIsGenerated());
      }
      if (!other.getLanguage().isEmpty()) {
        language_ = other.language_;
        onChanged();
      }
      if (!other.sources_.isEmpty()) {
        if (sources_.isEmpty()) {
          sources_ = other.sources_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureSourcesIsMutable();
          sources_.addAll(other.sources_);
        }
        onChanged();
      }
      if (!other.defines_.isEmpty()) {
        if (defines_.isEmpty()) {
          defines_ = other.defines_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureDefinesIsMutable();
          defines_.addAll(other.defines_);
        }
        onChanged();
      }
      if (includePathBuilder_ == null) {
        if (!other.includePath_.isEmpty()) {
          if (includePath_.isEmpty()) {
            includePath_ = other.includePath_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureIncludePathIsMutable();
            includePath_.addAll(other.includePath_);
          }
          onChanged();
        }
      } else {
        if (!other.includePath_.isEmpty()) {
          if (includePathBuilder_.isEmpty()) {
            includePathBuilder_.dispose();
            includePathBuilder_ = null;
            includePath_ = other.includePath_;
            bitField0_ = (bitField0_ & ~0x00000020);
            includePathBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getIncludePathFieldBuilder() : null;
          } else {
            includePathBuilder_.addAllMessages(other.includePath_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.jomofisher.cmakeserver.model.FileGroup parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.jomofisher.cmakeserver.model.FileGroup) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object compileFlags_ = "";
    /**
     * <code>optional string compileFlags = 1;</code>
     */
    public java.lang.String getCompileFlags() {
      java.lang.Object ref = compileFlags_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        compileFlags_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string compileFlags = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCompileFlagsBytes() {
      java.lang.Object ref = compileFlags_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        compileFlags_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string compileFlags = 1;</code>
     */
    public Builder setCompileFlags(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      compileFlags_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string compileFlags = 1;</code>
     */
    public Builder clearCompileFlags() {
      
      compileFlags_ = getDefaultInstance().getCompileFlags();
      onChanged();
      return this;
    }
    /**
     * <code>optional string compileFlags = 1;</code>
     */
    public Builder setCompileFlagsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      compileFlags_ = value;
      onChanged();
      return this;
    }

    private boolean isGenerated_ ;
    /**
     * <code>optional bool isGenerated = 2;</code>
     */
    public boolean getIsGenerated() {
      return isGenerated_;
    }
    /**
     * <code>optional bool isGenerated = 2;</code>
     */
    public Builder setIsGenerated(boolean value) {
      
      isGenerated_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool isGenerated = 2;</code>
     */
    public Builder clearIsGenerated() {
      
      isGenerated_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object language_ = "";
    /**
     * <code>optional string language = 3;</code>
     */
    public java.lang.String getLanguage() {
      java.lang.Object ref = language_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        language_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string language = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string language = 3;</code>
     */
    public Builder setLanguage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      language_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string language = 3;</code>
     */
    public Builder clearLanguage() {
      
      language_ = getDefaultInstance().getLanguage();
      onChanged();
      return this;
    }
    /**
     * <code>optional string language = 3;</code>
     */
    public Builder setLanguageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      language_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList sources_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureSourcesIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        sources_ = new com.google.protobuf.LazyStringArrayList(sources_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <code>repeated string sources = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSourcesList() {
      return sources_.getUnmodifiableView();
    }
    /**
     * <code>repeated string sources = 4;</code>
     */
    public int getSourcesCount() {
      return sources_.size();
    }
    /**
     * <code>repeated string sources = 4;</code>
     */
    public java.lang.String getSources(int index) {
      return sources_.get(index);
    }
    /**
     * <code>repeated string sources = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSourcesBytes(int index) {
      return sources_.getByteString(index);
    }
    /**
     * <code>repeated string sources = 4;</code>
     */
    public Builder setSources(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSourcesIsMutable();
      sources_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string sources = 4;</code>
     */
    public Builder addSources(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSourcesIsMutable();
      sources_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string sources = 4;</code>
     */
    public Builder addAllSources(
        java.lang.Iterable<java.lang.String> values) {
      ensureSourcesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, sources_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string sources = 4;</code>
     */
    public Builder clearSources() {
      sources_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string sources = 4;</code>
     */
    public Builder addSourcesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureSourcesIsMutable();
      sources_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList defines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureDefinesIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        defines_ = new com.google.protobuf.LazyStringArrayList(defines_);
        bitField0_ |= 0x00000010;
       }
    }
    /**
     * <code>repeated string defines = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDefinesList() {
      return defines_.getUnmodifiableView();
    }
    /**
     * <code>repeated string defines = 5;</code>
     */
    public int getDefinesCount() {
      return defines_.size();
    }
    /**
     * <code>repeated string defines = 5;</code>
     */
    public java.lang.String getDefines(int index) {
      return defines_.get(index);
    }
    /**
     * <code>repeated string defines = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDefinesBytes(int index) {
      return defines_.getByteString(index);
    }
    /**
     * <code>repeated string defines = 5;</code>
     */
    public Builder setDefines(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDefinesIsMutable();
      defines_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string defines = 5;</code>
     */
    public Builder addDefines(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDefinesIsMutable();
      defines_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string defines = 5;</code>
     */
    public Builder addAllDefines(
        java.lang.Iterable<java.lang.String> values) {
      ensureDefinesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, defines_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string defines = 5;</code>
     */
    public Builder clearDefines() {
      defines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string defines = 5;</code>
     */
    public Builder addDefinesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureDefinesIsMutable();
      defines_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<com.jomofisher.cmakeserver.model.IncludePath> includePath_ =
      java.util.Collections.emptyList();
    private void ensureIncludePathIsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        includePath_ = new java.util.ArrayList<com.jomofisher.cmakeserver.model.IncludePath>(includePath_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.jomofisher.cmakeserver.model.IncludePath, com.jomofisher.cmakeserver.model.IncludePath.Builder, com.jomofisher.cmakeserver.model.IncludePathOrBuilder> includePathBuilder_;

    /**
     * <code>repeated .IncludePath includePath = 6;</code>
     */
    public java.util.List<com.jomofisher.cmakeserver.model.IncludePath> getIncludePathList() {
      if (includePathBuilder_ == null) {
        return java.util.Collections.unmodifiableList(includePath_);
      } else {
        return includePathBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .IncludePath includePath = 6;</code>
     */
    public int getIncludePathCount() {
      if (includePathBuilder_ == null) {
        return includePath_.size();
      } else {
        return includePathBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .IncludePath includePath = 6;</code>
     */
    public com.jomofisher.cmakeserver.model.IncludePath getIncludePath(int index) {
      if (includePathBuilder_ == null) {
        return includePath_.get(index);
      } else {
        return includePathBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .IncludePath includePath = 6;</code>
     */
    public Builder setIncludePath(
        int index, com.jomofisher.cmakeserver.model.IncludePath value) {
      if (includePathBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIncludePathIsMutable();
        includePath_.set(index, value);
        onChanged();
      } else {
        includePathBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .IncludePath includePath = 6;</code>
     */
    public Builder setIncludePath(
        int index, com.jomofisher.cmakeserver.model.IncludePath.Builder builderForValue) {
      if (includePathBuilder_ == null) {
        ensureIncludePathIsMutable();
        includePath_.set(index, builderForValue.build());
        onChanged();
      } else {
        includePathBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IncludePath includePath = 6;</code>
     */
    public Builder addIncludePath(com.jomofisher.cmakeserver.model.IncludePath value) {
      if (includePathBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIncludePathIsMutable();
        includePath_.add(value);
        onChanged();
      } else {
        includePathBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .IncludePath includePath = 6;</code>
     */
    public Builder addIncludePath(
        int index, com.jomofisher.cmakeserver.model.IncludePath value) {
      if (includePathBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIncludePathIsMutable();
        includePath_.add(index, value);
        onChanged();
      } else {
        includePathBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .IncludePath includePath = 6;</code>
     */
    public Builder addIncludePath(
        com.jomofisher.cmakeserver.model.IncludePath.Builder builderForValue) {
      if (includePathBuilder_ == null) {
        ensureIncludePathIsMutable();
        includePath_.add(builderForValue.build());
        onChanged();
      } else {
        includePathBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IncludePath includePath = 6;</code>
     */
    public Builder addIncludePath(
        int index, com.jomofisher.cmakeserver.model.IncludePath.Builder builderForValue) {
      if (includePathBuilder_ == null) {
        ensureIncludePathIsMutable();
        includePath_.add(index, builderForValue.build());
        onChanged();
      } else {
        includePathBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IncludePath includePath = 6;</code>
     */
    public Builder addAllIncludePath(
        java.lang.Iterable<? extends com.jomofisher.cmakeserver.model.IncludePath> values) {
      if (includePathBuilder_ == null) {
        ensureIncludePathIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, includePath_);
        onChanged();
      } else {
        includePathBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .IncludePath includePath = 6;</code>
     */
    public Builder clearIncludePath() {
      if (includePathBuilder_ == null) {
        includePath_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        includePathBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .IncludePath includePath = 6;</code>
     */
    public Builder removeIncludePath(int index) {
      if (includePathBuilder_ == null) {
        ensureIncludePathIsMutable();
        includePath_.remove(index);
        onChanged();
      } else {
        includePathBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .IncludePath includePath = 6;</code>
     */
    public com.jomofisher.cmakeserver.model.IncludePath.Builder getIncludePathBuilder(
        int index) {
      return getIncludePathFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .IncludePath includePath = 6;</code>
     */
    public com.jomofisher.cmakeserver.model.IncludePathOrBuilder getIncludePathOrBuilder(
        int index) {
      if (includePathBuilder_ == null) {
        return includePath_.get(index);  } else {
        return includePathBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .IncludePath includePath = 6;</code>
     */
    public java.util.List<? extends com.jomofisher.cmakeserver.model.IncludePathOrBuilder> 
         getIncludePathOrBuilderList() {
      if (includePathBuilder_ != null) {
        return includePathBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(includePath_);
      }
    }
    /**
     * <code>repeated .IncludePath includePath = 6;</code>
     */
    public com.jomofisher.cmakeserver.model.IncludePath.Builder addIncludePathBuilder() {
      return getIncludePathFieldBuilder().addBuilder(
          com.jomofisher.cmakeserver.model.IncludePath.getDefaultInstance());
    }
    /**
     * <code>repeated .IncludePath includePath = 6;</code>
     */
    public com.jomofisher.cmakeserver.model.IncludePath.Builder addIncludePathBuilder(
        int index) {
      return getIncludePathFieldBuilder().addBuilder(
          index, com.jomofisher.cmakeserver.model.IncludePath.getDefaultInstance());
    }
    /**
     * <code>repeated .IncludePath includePath = 6;</code>
     */
    public java.util.List<com.jomofisher.cmakeserver.model.IncludePath.Builder> 
         getIncludePathBuilderList() {
      return getIncludePathFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.jomofisher.cmakeserver.model.IncludePath, com.jomofisher.cmakeserver.model.IncludePath.Builder, com.jomofisher.cmakeserver.model.IncludePathOrBuilder> 
        getIncludePathFieldBuilder() {
      if (includePathBuilder_ == null) {
        includePathBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.jomofisher.cmakeserver.model.IncludePath, com.jomofisher.cmakeserver.model.IncludePath.Builder, com.jomofisher.cmakeserver.model.IncludePathOrBuilder>(
                includePath_,
                ((bitField0_ & 0x00000020) == 0x00000020),
                getParentForChildren(),
                isClean());
        includePath_ = null;
      }
      return includePathBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:FileGroup)
  }

  // @@protoc_insertion_point(class_scope:FileGroup)
  private static final com.jomofisher.cmakeserver.model.FileGroup DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.jomofisher.cmakeserver.model.FileGroup();
  }

  public static com.jomofisher.cmakeserver.model.FileGroup getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FileGroup>
      PARSER = new com.google.protobuf.AbstractParser<FileGroup>() {
    public FileGroup parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileGroup(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FileGroup> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FileGroup> getParserForType() {
    return PARSER;
  }

  public com.jomofisher.cmakeserver.model.FileGroup getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

