// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.1.0.proto

package com.jomofisher.cmakeserver.model;

public interface GeneratorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Generator)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional bool platformSupport = 2;</code>
   */
  boolean getPlatformSupport();

  /**
   * <code>optional bool toolsetSupport = 3;</code>
   */
  boolean getToolsetSupport();

  /**
   * <code>repeated string extraGenerators = 4;</code>
   */
  java.util.List<java.lang.String>
      getExtraGeneratorsList();
  /**
   * <code>repeated string extraGenerators = 4;</code>
   */
  int getExtraGeneratorsCount();
  /**
   * <code>repeated string extraGenerators = 4;</code>
   */
  java.lang.String getExtraGenerators(int index);
  /**
   * <code>repeated string extraGenerators = 4;</code>
   */
  com.google.protobuf.ByteString
      getExtraGeneratorsBytes(int index);
}
