// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.1.0.proto

package com.jomofisher.cmakeserver.model;

/**
 * Protobuf type {@code GlobalSettingsReply}
 */
public  final class GlobalSettingsReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GlobalSettingsReply)
    GlobalSettingsReplyOrBuilder {
  // Use GlobalSettingsReply.newBuilder() to construct.
  private GlobalSettingsReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GlobalSettingsReply() {
    type_ = "";
    cookie_ = "";
    inReplyTo_ = "";
    buildDirectory_ = "";
    checkSystemVars_ = false;
    debugOutput_ = false;
    extraGenerator_ = "";
    generator_ = "";
    sourceDirectory_ = "";
    trace_ = false;
    traceExpand_ = false;
    warnUninitialized_ = false;
    warnUnused_ = false;
    warnUnusedCli_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GlobalSettingsReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            cookie_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            inReplyTo_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            buildDirectory_ = s;
            break;
          }
          case 40: {

            checkSystemVars_ = input.readBool();
            break;
          }
          case 48: {

            debugOutput_ = input.readBool();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            extraGenerator_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            generator_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            sourceDirectory_ = s;
            break;
          }
          case 80: {

            trace_ = input.readBool();
            break;
          }
          case 88: {

            traceExpand_ = input.readBool();
            break;
          }
          case 96: {

            warnUninitialized_ = input.readBool();
            break;
          }
          case 104: {

            warnUnused_ = input.readBool();
            break;
          }
          case 112: {

            warnUnusedCli_ = input.readBool();
            break;
          }
          case 122: {
            com.jomofisher.cmakeserver.model.Capabilities.Builder subBuilder = null;
            if (capabilities_ != null) {
              subBuilder = capabilities_.toBuilder();
            }
            capabilities_ = input.readMessage(com.jomofisher.cmakeserver.model.Capabilities.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(capabilities_);
              capabilities_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jomofisher.cmakeserver.model.Messages10.internal_static_GlobalSettingsReply_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jomofisher.cmakeserver.model.Messages10.internal_static_GlobalSettingsReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jomofisher.cmakeserver.model.GlobalSettingsReply.class, com.jomofisher.cmakeserver.model.GlobalSettingsReply.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object type_;
  /**
   * <code>optional string type = 1;</code>
   */
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>optional string type = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COOKIE_FIELD_NUMBER = 2;
  private volatile java.lang.Object cookie_;
  /**
   * <code>optional string cookie = 2;</code>
   */
  public java.lang.String getCookie() {
    java.lang.Object ref = cookie_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cookie_ = s;
      return s;
    }
  }
  /**
   * <code>optional string cookie = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCookieBytes() {
    java.lang.Object ref = cookie_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cookie_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INREPLYTO_FIELD_NUMBER = 3;
  private volatile java.lang.Object inReplyTo_;
  /**
   * <code>optional string inReplyTo = 3;</code>
   */
  public java.lang.String getInReplyTo() {
    java.lang.Object ref = inReplyTo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      inReplyTo_ = s;
      return s;
    }
  }
  /**
   * <code>optional string inReplyTo = 3;</code>
   */
  public com.google.protobuf.ByteString
      getInReplyToBytes() {
    java.lang.Object ref = inReplyTo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      inReplyTo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BUILDDIRECTORY_FIELD_NUMBER = 4;
  private volatile java.lang.Object buildDirectory_;
  /**
   * <code>optional string buildDirectory = 4;</code>
   */
  public java.lang.String getBuildDirectory() {
    java.lang.Object ref = buildDirectory_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      buildDirectory_ = s;
      return s;
    }
  }
  /**
   * <code>optional string buildDirectory = 4;</code>
   */
  public com.google.protobuf.ByteString
      getBuildDirectoryBytes() {
    java.lang.Object ref = buildDirectory_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      buildDirectory_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHECKSYSTEMVARS_FIELD_NUMBER = 5;
  private boolean checkSystemVars_;
  /**
   * <code>optional bool checkSystemVars = 5;</code>
   */
  public boolean getCheckSystemVars() {
    return checkSystemVars_;
  }

  public static final int DEBUGOUTPUT_FIELD_NUMBER = 6;
  private boolean debugOutput_;
  /**
   * <code>optional bool debugOutput = 6;</code>
   */
  public boolean getDebugOutput() {
    return debugOutput_;
  }

  public static final int EXTRAGENERATOR_FIELD_NUMBER = 7;
  private volatile java.lang.Object extraGenerator_;
  /**
   * <code>optional string extraGenerator = 7;</code>
   */
  public java.lang.String getExtraGenerator() {
    java.lang.Object ref = extraGenerator_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      extraGenerator_ = s;
      return s;
    }
  }
  /**
   * <code>optional string extraGenerator = 7;</code>
   */
  public com.google.protobuf.ByteString
      getExtraGeneratorBytes() {
    java.lang.Object ref = extraGenerator_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      extraGenerator_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENERATOR_FIELD_NUMBER = 8;
  private volatile java.lang.Object generator_;
  /**
   * <code>optional string generator = 8;</code>
   */
  public java.lang.String getGenerator() {
    java.lang.Object ref = generator_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      generator_ = s;
      return s;
    }
  }
  /**
   * <code>optional string generator = 8;</code>
   */
  public com.google.protobuf.ByteString
      getGeneratorBytes() {
    java.lang.Object ref = generator_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      generator_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCEDIRECTORY_FIELD_NUMBER = 9;
  private volatile java.lang.Object sourceDirectory_;
  /**
   * <code>optional string sourceDirectory = 9;</code>
   */
  public java.lang.String getSourceDirectory() {
    java.lang.Object ref = sourceDirectory_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceDirectory_ = s;
      return s;
    }
  }
  /**
   * <code>optional string sourceDirectory = 9;</code>
   */
  public com.google.protobuf.ByteString
      getSourceDirectoryBytes() {
    java.lang.Object ref = sourceDirectory_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceDirectory_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRACE_FIELD_NUMBER = 10;
  private boolean trace_;
  /**
   * <code>optional bool trace = 10;</code>
   */
  public boolean getTrace() {
    return trace_;
  }

  public static final int TRACEEXPAND_FIELD_NUMBER = 11;
  private boolean traceExpand_;
  /**
   * <code>optional bool traceExpand = 11;</code>
   */
  public boolean getTraceExpand() {
    return traceExpand_;
  }

  public static final int WARNUNINITIALIZED_FIELD_NUMBER = 12;
  private boolean warnUninitialized_;
  /**
   * <code>optional bool warnUninitialized = 12;</code>
   */
  public boolean getWarnUninitialized() {
    return warnUninitialized_;
  }

  public static final int WARNUNUSED_FIELD_NUMBER = 13;
  private boolean warnUnused_;
  /**
   * <code>optional bool warnUnused = 13;</code>
   */
  public boolean getWarnUnused() {
    return warnUnused_;
  }

  public static final int WARNUNUSEDCLI_FIELD_NUMBER = 14;
  private boolean warnUnusedCli_;
  /**
   * <code>optional bool warnUnusedCli = 14;</code>
   */
  public boolean getWarnUnusedCli() {
    return warnUnusedCli_;
  }

  public static final int CAPABILITIES_FIELD_NUMBER = 15;
  private com.jomofisher.cmakeserver.model.Capabilities capabilities_;
  /**
   * <code>optional .Capabilities capabilities = 15;</code>
   */
  public boolean hasCapabilities() {
    return capabilities_ != null;
  }
  /**
   * <code>optional .Capabilities capabilities = 15;</code>
   */
  public com.jomofisher.cmakeserver.model.Capabilities getCapabilities() {
    return capabilities_ == null ? com.jomofisher.cmakeserver.model.Capabilities.getDefaultInstance() : capabilities_;
  }
  /**
   * <code>optional .Capabilities capabilities = 15;</code>
   */
  public com.jomofisher.cmakeserver.model.CapabilitiesOrBuilder getCapabilitiesOrBuilder() {
    return getCapabilities();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
    }
    if (!getCookieBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cookie_);
    }
    if (!getInReplyToBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, inReplyTo_);
    }
    if (!getBuildDirectoryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, buildDirectory_);
    }
    if (checkSystemVars_ != false) {
      output.writeBool(5, checkSystemVars_);
    }
    if (debugOutput_ != false) {
      output.writeBool(6, debugOutput_);
    }
    if (!getExtraGeneratorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, extraGenerator_);
    }
    if (!getGeneratorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, generator_);
    }
    if (!getSourceDirectoryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, sourceDirectory_);
    }
    if (trace_ != false) {
      output.writeBool(10, trace_);
    }
    if (traceExpand_ != false) {
      output.writeBool(11, traceExpand_);
    }
    if (warnUninitialized_ != false) {
      output.writeBool(12, warnUninitialized_);
    }
    if (warnUnused_ != false) {
      output.writeBool(13, warnUnused_);
    }
    if (warnUnusedCli_ != false) {
      output.writeBool(14, warnUnusedCli_);
    }
    if (capabilities_ != null) {
      output.writeMessage(15, getCapabilities());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
    }
    if (!getCookieBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cookie_);
    }
    if (!getInReplyToBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, inReplyTo_);
    }
    if (!getBuildDirectoryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, buildDirectory_);
    }
    if (checkSystemVars_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, checkSystemVars_);
    }
    if (debugOutput_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, debugOutput_);
    }
    if (!getExtraGeneratorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, extraGenerator_);
    }
    if (!getGeneratorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, generator_);
    }
    if (!getSourceDirectoryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, sourceDirectory_);
    }
    if (trace_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, trace_);
    }
    if (traceExpand_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(11, traceExpand_);
    }
    if (warnUninitialized_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(12, warnUninitialized_);
    }
    if (warnUnused_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(13, warnUnused_);
    }
    if (warnUnusedCli_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(14, warnUnusedCli_);
    }
    if (capabilities_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(15, getCapabilities());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.jomofisher.cmakeserver.model.GlobalSettingsReply)) {
      return super.equals(obj);
    }
    com.jomofisher.cmakeserver.model.GlobalSettingsReply other = (com.jomofisher.cmakeserver.model.GlobalSettingsReply) obj;

    boolean result = true;
    result = result && getType()
        .equals(other.getType());
    result = result && getCookie()
        .equals(other.getCookie());
    result = result && getInReplyTo()
        .equals(other.getInReplyTo());
    result = result && getBuildDirectory()
        .equals(other.getBuildDirectory());
    result = result && (getCheckSystemVars()
        == other.getCheckSystemVars());
    result = result && (getDebugOutput()
        == other.getDebugOutput());
    result = result && getExtraGenerator()
        .equals(other.getExtraGenerator());
    result = result && getGenerator()
        .equals(other.getGenerator());
    result = result && getSourceDirectory()
        .equals(other.getSourceDirectory());
    result = result && (getTrace()
        == other.getTrace());
    result = result && (getTraceExpand()
        == other.getTraceExpand());
    result = result && (getWarnUninitialized()
        == other.getWarnUninitialized());
    result = result && (getWarnUnused()
        == other.getWarnUnused());
    result = result && (getWarnUnusedCli()
        == other.getWarnUnusedCli());
    result = result && (hasCapabilities() == other.hasCapabilities());
    if (hasCapabilities()) {
      result = result && getCapabilities()
          .equals(other.getCapabilities());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + COOKIE_FIELD_NUMBER;
    hash = (53 * hash) + getCookie().hashCode();
    hash = (37 * hash) + INREPLYTO_FIELD_NUMBER;
    hash = (53 * hash) + getInReplyTo().hashCode();
    hash = (37 * hash) + BUILDDIRECTORY_FIELD_NUMBER;
    hash = (53 * hash) + getBuildDirectory().hashCode();
    hash = (37 * hash) + CHECKSYSTEMVARS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCheckSystemVars());
    hash = (37 * hash) + DEBUGOUTPUT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDebugOutput());
    hash = (37 * hash) + EXTRAGENERATOR_FIELD_NUMBER;
    hash = (53 * hash) + getExtraGenerator().hashCode();
    hash = (37 * hash) + GENERATOR_FIELD_NUMBER;
    hash = (53 * hash) + getGenerator().hashCode();
    hash = (37 * hash) + SOURCEDIRECTORY_FIELD_NUMBER;
    hash = (53 * hash) + getSourceDirectory().hashCode();
    hash = (37 * hash) + TRACE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTrace());
    hash = (37 * hash) + TRACEEXPAND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTraceExpand());
    hash = (37 * hash) + WARNUNINITIALIZED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getWarnUninitialized());
    hash = (37 * hash) + WARNUNUSED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getWarnUnused());
    hash = (37 * hash) + WARNUNUSEDCLI_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getWarnUnusedCli());
    if (hasCapabilities()) {
      hash = (37 * hash) + CAPABILITIES_FIELD_NUMBER;
      hash = (53 * hash) + getCapabilities().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.jomofisher.cmakeserver.model.GlobalSettingsReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jomofisher.cmakeserver.model.GlobalSettingsReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.GlobalSettingsReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jomofisher.cmakeserver.model.GlobalSettingsReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.GlobalSettingsReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jomofisher.cmakeserver.model.GlobalSettingsReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.GlobalSettingsReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.jomofisher.cmakeserver.model.GlobalSettingsReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.GlobalSettingsReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jomofisher.cmakeserver.model.GlobalSettingsReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.jomofisher.cmakeserver.model.GlobalSettingsReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GlobalSettingsReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GlobalSettingsReply)
      com.jomofisher.cmakeserver.model.GlobalSettingsReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jomofisher.cmakeserver.model.Messages10.internal_static_GlobalSettingsReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jomofisher.cmakeserver.model.Messages10.internal_static_GlobalSettingsReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jomofisher.cmakeserver.model.GlobalSettingsReply.class, com.jomofisher.cmakeserver.model.GlobalSettingsReply.Builder.class);
    }

    // Construct using com.jomofisher.cmakeserver.model.GlobalSettingsReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      type_ = "";

      cookie_ = "";

      inReplyTo_ = "";

      buildDirectory_ = "";

      checkSystemVars_ = false;

      debugOutput_ = false;

      extraGenerator_ = "";

      generator_ = "";

      sourceDirectory_ = "";

      trace_ = false;

      traceExpand_ = false;

      warnUninitialized_ = false;

      warnUnused_ = false;

      warnUnusedCli_ = false;

      if (capabilitiesBuilder_ == null) {
        capabilities_ = null;
      } else {
        capabilities_ = null;
        capabilitiesBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jomofisher.cmakeserver.model.Messages10.internal_static_GlobalSettingsReply_descriptor;
    }

    public com.jomofisher.cmakeserver.model.GlobalSettingsReply getDefaultInstanceForType() {
      return com.jomofisher.cmakeserver.model.GlobalSettingsReply.getDefaultInstance();
    }

    public com.jomofisher.cmakeserver.model.GlobalSettingsReply build() {
      com.jomofisher.cmakeserver.model.GlobalSettingsReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.jomofisher.cmakeserver.model.GlobalSettingsReply buildPartial() {
      com.jomofisher.cmakeserver.model.GlobalSettingsReply result = new com.jomofisher.cmakeserver.model.GlobalSettingsReply(this);
      result.type_ = type_;
      result.cookie_ = cookie_;
      result.inReplyTo_ = inReplyTo_;
      result.buildDirectory_ = buildDirectory_;
      result.checkSystemVars_ = checkSystemVars_;
      result.debugOutput_ = debugOutput_;
      result.extraGenerator_ = extraGenerator_;
      result.generator_ = generator_;
      result.sourceDirectory_ = sourceDirectory_;
      result.trace_ = trace_;
      result.traceExpand_ = traceExpand_;
      result.warnUninitialized_ = warnUninitialized_;
      result.warnUnused_ = warnUnused_;
      result.warnUnusedCli_ = warnUnusedCli_;
      if (capabilitiesBuilder_ == null) {
        result.capabilities_ = capabilities_;
      } else {
        result.capabilities_ = capabilitiesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jomofisher.cmakeserver.model.GlobalSettingsReply) {
        return mergeFrom((com.jomofisher.cmakeserver.model.GlobalSettingsReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jomofisher.cmakeserver.model.GlobalSettingsReply other) {
      if (other == com.jomofisher.cmakeserver.model.GlobalSettingsReply.getDefaultInstance()) return this;
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (!other.getCookie().isEmpty()) {
        cookie_ = other.cookie_;
        onChanged();
      }
      if (!other.getInReplyTo().isEmpty()) {
        inReplyTo_ = other.inReplyTo_;
        onChanged();
      }
      if (!other.getBuildDirectory().isEmpty()) {
        buildDirectory_ = other.buildDirectory_;
        onChanged();
      }
      if (other.getCheckSystemVars() != false) {
        setCheckSystemVars(other.getCheckSystemVars());
      }
      if (other.getDebugOutput() != false) {
        setDebugOutput(other.getDebugOutput());
      }
      if (!other.getExtraGenerator().isEmpty()) {
        extraGenerator_ = other.extraGenerator_;
        onChanged();
      }
      if (!other.getGenerator().isEmpty()) {
        generator_ = other.generator_;
        onChanged();
      }
      if (!other.getSourceDirectory().isEmpty()) {
        sourceDirectory_ = other.sourceDirectory_;
        onChanged();
      }
      if (other.getTrace() != false) {
        setTrace(other.getTrace());
      }
      if (other.getTraceExpand() != false) {
        setTraceExpand(other.getTraceExpand());
      }
      if (other.getWarnUninitialized() != false) {
        setWarnUninitialized(other.getWarnUninitialized());
      }
      if (other.getWarnUnused() != false) {
        setWarnUnused(other.getWarnUnused());
      }
      if (other.getWarnUnusedCli() != false) {
        setWarnUnusedCli(other.getWarnUnusedCli());
      }
      if (other.hasCapabilities()) {
        mergeCapabilities(other.getCapabilities());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.jomofisher.cmakeserver.model.GlobalSettingsReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.jomofisher.cmakeserver.model.GlobalSettingsReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>optional string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string type = 1;</code>
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string type = 1;</code>
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>optional string type = 1;</code>
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cookie_ = "";
    /**
     * <code>optional string cookie = 2;</code>
     */
    public java.lang.String getCookie() {
      java.lang.Object ref = cookie_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cookie_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string cookie = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCookieBytes() {
      java.lang.Object ref = cookie_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cookie_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string cookie = 2;</code>
     */
    public Builder setCookie(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cookie_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string cookie = 2;</code>
     */
    public Builder clearCookie() {
      
      cookie_ = getDefaultInstance().getCookie();
      onChanged();
      return this;
    }
    /**
     * <code>optional string cookie = 2;</code>
     */
    public Builder setCookieBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cookie_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object inReplyTo_ = "";
    /**
     * <code>optional string inReplyTo = 3;</code>
     */
    public java.lang.String getInReplyTo() {
      java.lang.Object ref = inReplyTo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        inReplyTo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string inReplyTo = 3;</code>
     */
    public com.google.protobuf.ByteString
        getInReplyToBytes() {
      java.lang.Object ref = inReplyTo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        inReplyTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string inReplyTo = 3;</code>
     */
    public Builder setInReplyTo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      inReplyTo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string inReplyTo = 3;</code>
     */
    public Builder clearInReplyTo() {
      
      inReplyTo_ = getDefaultInstance().getInReplyTo();
      onChanged();
      return this;
    }
    /**
     * <code>optional string inReplyTo = 3;</code>
     */
    public Builder setInReplyToBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      inReplyTo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object buildDirectory_ = "";
    /**
     * <code>optional string buildDirectory = 4;</code>
     */
    public java.lang.String getBuildDirectory() {
      java.lang.Object ref = buildDirectory_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buildDirectory_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string buildDirectory = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBuildDirectoryBytes() {
      java.lang.Object ref = buildDirectory_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buildDirectory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string buildDirectory = 4;</code>
     */
    public Builder setBuildDirectory(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      buildDirectory_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string buildDirectory = 4;</code>
     */
    public Builder clearBuildDirectory() {
      
      buildDirectory_ = getDefaultInstance().getBuildDirectory();
      onChanged();
      return this;
    }
    /**
     * <code>optional string buildDirectory = 4;</code>
     */
    public Builder setBuildDirectoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      buildDirectory_ = value;
      onChanged();
      return this;
    }

    private boolean checkSystemVars_ ;
    /**
     * <code>optional bool checkSystemVars = 5;</code>
     */
    public boolean getCheckSystemVars() {
      return checkSystemVars_;
    }
    /**
     * <code>optional bool checkSystemVars = 5;</code>
     */
    public Builder setCheckSystemVars(boolean value) {
      
      checkSystemVars_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool checkSystemVars = 5;</code>
     */
    public Builder clearCheckSystemVars() {
      
      checkSystemVars_ = false;
      onChanged();
      return this;
    }

    private boolean debugOutput_ ;
    /**
     * <code>optional bool debugOutput = 6;</code>
     */
    public boolean getDebugOutput() {
      return debugOutput_;
    }
    /**
     * <code>optional bool debugOutput = 6;</code>
     */
    public Builder setDebugOutput(boolean value) {
      
      debugOutput_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool debugOutput = 6;</code>
     */
    public Builder clearDebugOutput() {
      
      debugOutput_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object extraGenerator_ = "";
    /**
     * <code>optional string extraGenerator = 7;</code>
     */
    public java.lang.String getExtraGenerator() {
      java.lang.Object ref = extraGenerator_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extraGenerator_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string extraGenerator = 7;</code>
     */
    public com.google.protobuf.ByteString
        getExtraGeneratorBytes() {
      java.lang.Object ref = extraGenerator_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extraGenerator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string extraGenerator = 7;</code>
     */
    public Builder setExtraGenerator(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      extraGenerator_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string extraGenerator = 7;</code>
     */
    public Builder clearExtraGenerator() {
      
      extraGenerator_ = getDefaultInstance().getExtraGenerator();
      onChanged();
      return this;
    }
    /**
     * <code>optional string extraGenerator = 7;</code>
     */
    public Builder setExtraGeneratorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      extraGenerator_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object generator_ = "";
    /**
     * <code>optional string generator = 8;</code>
     */
    public java.lang.String getGenerator() {
      java.lang.Object ref = generator_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        generator_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string generator = 8;</code>
     */
    public com.google.protobuf.ByteString
        getGeneratorBytes() {
      java.lang.Object ref = generator_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        generator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string generator = 8;</code>
     */
    public Builder setGenerator(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      generator_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string generator = 8;</code>
     */
    public Builder clearGenerator() {
      
      generator_ = getDefaultInstance().getGenerator();
      onChanged();
      return this;
    }
    /**
     * <code>optional string generator = 8;</code>
     */
    public Builder setGeneratorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      generator_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sourceDirectory_ = "";
    /**
     * <code>optional string sourceDirectory = 9;</code>
     */
    public java.lang.String getSourceDirectory() {
      java.lang.Object ref = sourceDirectory_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceDirectory_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sourceDirectory = 9;</code>
     */
    public com.google.protobuf.ByteString
        getSourceDirectoryBytes() {
      java.lang.Object ref = sourceDirectory_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceDirectory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sourceDirectory = 9;</code>
     */
    public Builder setSourceDirectory(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceDirectory_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sourceDirectory = 9;</code>
     */
    public Builder clearSourceDirectory() {
      
      sourceDirectory_ = getDefaultInstance().getSourceDirectory();
      onChanged();
      return this;
    }
    /**
     * <code>optional string sourceDirectory = 9;</code>
     */
    public Builder setSourceDirectoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceDirectory_ = value;
      onChanged();
      return this;
    }

    private boolean trace_ ;
    /**
     * <code>optional bool trace = 10;</code>
     */
    public boolean getTrace() {
      return trace_;
    }
    /**
     * <code>optional bool trace = 10;</code>
     */
    public Builder setTrace(boolean value) {
      
      trace_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool trace = 10;</code>
     */
    public Builder clearTrace() {
      
      trace_ = false;
      onChanged();
      return this;
    }

    private boolean traceExpand_ ;
    /**
     * <code>optional bool traceExpand = 11;</code>
     */
    public boolean getTraceExpand() {
      return traceExpand_;
    }
    /**
     * <code>optional bool traceExpand = 11;</code>
     */
    public Builder setTraceExpand(boolean value) {
      
      traceExpand_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool traceExpand = 11;</code>
     */
    public Builder clearTraceExpand() {
      
      traceExpand_ = false;
      onChanged();
      return this;
    }

    private boolean warnUninitialized_ ;
    /**
     * <code>optional bool warnUninitialized = 12;</code>
     */
    public boolean getWarnUninitialized() {
      return warnUninitialized_;
    }
    /**
     * <code>optional bool warnUninitialized = 12;</code>
     */
    public Builder setWarnUninitialized(boolean value) {
      
      warnUninitialized_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool warnUninitialized = 12;</code>
     */
    public Builder clearWarnUninitialized() {
      
      warnUninitialized_ = false;
      onChanged();
      return this;
    }

    private boolean warnUnused_ ;
    /**
     * <code>optional bool warnUnused = 13;</code>
     */
    public boolean getWarnUnused() {
      return warnUnused_;
    }
    /**
     * <code>optional bool warnUnused = 13;</code>
     */
    public Builder setWarnUnused(boolean value) {
      
      warnUnused_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool warnUnused = 13;</code>
     */
    public Builder clearWarnUnused() {
      
      warnUnused_ = false;
      onChanged();
      return this;
    }

    private boolean warnUnusedCli_ ;
    /**
     * <code>optional bool warnUnusedCli = 14;</code>
     */
    public boolean getWarnUnusedCli() {
      return warnUnusedCli_;
    }
    /**
     * <code>optional bool warnUnusedCli = 14;</code>
     */
    public Builder setWarnUnusedCli(boolean value) {
      
      warnUnusedCli_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool warnUnusedCli = 14;</code>
     */
    public Builder clearWarnUnusedCli() {
      
      warnUnusedCli_ = false;
      onChanged();
      return this;
    }

    private com.jomofisher.cmakeserver.model.Capabilities capabilities_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.jomofisher.cmakeserver.model.Capabilities, com.jomofisher.cmakeserver.model.Capabilities.Builder, com.jomofisher.cmakeserver.model.CapabilitiesOrBuilder> capabilitiesBuilder_;
    /**
     * <code>optional .Capabilities capabilities = 15;</code>
     */
    public boolean hasCapabilities() {
      return capabilitiesBuilder_ != null || capabilities_ != null;
    }
    /**
     * <code>optional .Capabilities capabilities = 15;</code>
     */
    public com.jomofisher.cmakeserver.model.Capabilities getCapabilities() {
      if (capabilitiesBuilder_ == null) {
        return capabilities_ == null ? com.jomofisher.cmakeserver.model.Capabilities.getDefaultInstance() : capabilities_;
      } else {
        return capabilitiesBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .Capabilities capabilities = 15;</code>
     */
    public Builder setCapabilities(com.jomofisher.cmakeserver.model.Capabilities value) {
      if (capabilitiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        capabilities_ = value;
        onChanged();
      } else {
        capabilitiesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .Capabilities capabilities = 15;</code>
     */
    public Builder setCapabilities(
        com.jomofisher.cmakeserver.model.Capabilities.Builder builderForValue) {
      if (capabilitiesBuilder_ == null) {
        capabilities_ = builderForValue.build();
        onChanged();
      } else {
        capabilitiesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .Capabilities capabilities = 15;</code>
     */
    public Builder mergeCapabilities(com.jomofisher.cmakeserver.model.Capabilities value) {
      if (capabilitiesBuilder_ == null) {
        if (capabilities_ != null) {
          capabilities_ =
            com.jomofisher.cmakeserver.model.Capabilities.newBuilder(capabilities_).mergeFrom(value).buildPartial();
        } else {
          capabilities_ = value;
        }
        onChanged();
      } else {
        capabilitiesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .Capabilities capabilities = 15;</code>
     */
    public Builder clearCapabilities() {
      if (capabilitiesBuilder_ == null) {
        capabilities_ = null;
        onChanged();
      } else {
        capabilities_ = null;
        capabilitiesBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .Capabilities capabilities = 15;</code>
     */
    public com.jomofisher.cmakeserver.model.Capabilities.Builder getCapabilitiesBuilder() {
      
      onChanged();
      return getCapabilitiesFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .Capabilities capabilities = 15;</code>
     */
    public com.jomofisher.cmakeserver.model.CapabilitiesOrBuilder getCapabilitiesOrBuilder() {
      if (capabilitiesBuilder_ != null) {
        return capabilitiesBuilder_.getMessageOrBuilder();
      } else {
        return capabilities_ == null ?
            com.jomofisher.cmakeserver.model.Capabilities.getDefaultInstance() : capabilities_;
      }
    }
    /**
     * <code>optional .Capabilities capabilities = 15;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.jomofisher.cmakeserver.model.Capabilities, com.jomofisher.cmakeserver.model.Capabilities.Builder, com.jomofisher.cmakeserver.model.CapabilitiesOrBuilder> 
        getCapabilitiesFieldBuilder() {
      if (capabilitiesBuilder_ == null) {
        capabilitiesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.jomofisher.cmakeserver.model.Capabilities, com.jomofisher.cmakeserver.model.Capabilities.Builder, com.jomofisher.cmakeserver.model.CapabilitiesOrBuilder>(
                getCapabilities(),
                getParentForChildren(),
                isClean());
        capabilities_ = null;
      }
      return capabilitiesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:GlobalSettingsReply)
  }

  // @@protoc_insertion_point(class_scope:GlobalSettingsReply)
  private static final com.jomofisher.cmakeserver.model.GlobalSettingsReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.jomofisher.cmakeserver.model.GlobalSettingsReply();
  }

  public static com.jomofisher.cmakeserver.model.GlobalSettingsReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GlobalSettingsReply>
      PARSER = new com.google.protobuf.AbstractParser<GlobalSettingsReply>() {
    public GlobalSettingsReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GlobalSettingsReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GlobalSettingsReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GlobalSettingsReply> getParserForType() {
    return PARSER;
  }

  public com.jomofisher.cmakeserver.model.GlobalSettingsReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

