// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.1.0.proto

package com.jomofisher.cmakeserver.model;

public interface GlobalSettingsReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GlobalSettingsReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string type = 1;</code>
   */
  java.lang.String getType();
  /**
   * <code>optional string type = 1;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>optional string cookie = 2;</code>
   */
  java.lang.String getCookie();
  /**
   * <code>optional string cookie = 2;</code>
   */
  com.google.protobuf.ByteString
      getCookieBytes();

  /**
   * <code>optional string inReplyTo = 3;</code>
   */
  java.lang.String getInReplyTo();
  /**
   * <code>optional string inReplyTo = 3;</code>
   */
  com.google.protobuf.ByteString
      getInReplyToBytes();

  /**
   * <code>optional string buildDirectory = 4;</code>
   */
  java.lang.String getBuildDirectory();
  /**
   * <code>optional string buildDirectory = 4;</code>
   */
  com.google.protobuf.ByteString
      getBuildDirectoryBytes();

  /**
   * <code>optional bool checkSystemVars = 5;</code>
   */
  boolean getCheckSystemVars();

  /**
   * <code>optional bool debugOutput = 6;</code>
   */
  boolean getDebugOutput();

  /**
   * <code>optional string extraGenerator = 7;</code>
   */
  java.lang.String getExtraGenerator();
  /**
   * <code>optional string extraGenerator = 7;</code>
   */
  com.google.protobuf.ByteString
      getExtraGeneratorBytes();

  /**
   * <code>optional string generator = 8;</code>
   */
  java.lang.String getGenerator();
  /**
   * <code>optional string generator = 8;</code>
   */
  com.google.protobuf.ByteString
      getGeneratorBytes();

  /**
   * <code>optional string sourceDirectory = 9;</code>
   */
  java.lang.String getSourceDirectory();
  /**
   * <code>optional string sourceDirectory = 9;</code>
   */
  com.google.protobuf.ByteString
      getSourceDirectoryBytes();

  /**
   * <code>optional bool trace = 10;</code>
   */
  boolean getTrace();

  /**
   * <code>optional bool traceExpand = 11;</code>
   */
  boolean getTraceExpand();

  /**
   * <code>optional bool warnUninitialized = 12;</code>
   */
  boolean getWarnUninitialized();

  /**
   * <code>optional bool warnUnused = 13;</code>
   */
  boolean getWarnUnused();

  /**
   * <code>optional bool warnUnusedCli = 14;</code>
   */
  boolean getWarnUnusedCli();

  /**
   * <code>optional .Capabilities capabilities = 15;</code>
   */
  boolean hasCapabilities();
  /**
   * <code>optional .Capabilities capabilities = 15;</code>
   */
  com.jomofisher.cmakeserver.model.Capabilities getCapabilities();
  /**
   * <code>optional .Capabilities capabilities = 15;</code>
   */
  com.jomofisher.cmakeserver.model.CapabilitiesOrBuilder getCapabilitiesOrBuilder();
}
