// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.1.0.proto

package com.jomofisher.cmakeserver.model;

/**
 * Protobuf type {@code HandshakeMessage}
 */
public  final class HandshakeMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:HandshakeMessage)
    HandshakeMessageOrBuilder {
  // Use HandshakeMessage.newBuilder() to construct.
  private HandshakeMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HandshakeMessage() {
    type_ = "";
    cookie_ = "";
    sourceDirectory_ = "";
    buildDirectory_ = "";
    generator_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private HandshakeMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            cookie_ = s;
            break;
          }
          case 26: {
            com.jomofisher.cmakeserver.model.ProtocolVersion.Builder subBuilder = null;
            if (protocolVersion_ != null) {
              subBuilder = protocolVersion_.toBuilder();
            }
            protocolVersion_ = input.readMessage(com.jomofisher.cmakeserver.model.ProtocolVersion.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(protocolVersion_);
              protocolVersion_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            sourceDirectory_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            buildDirectory_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            generator_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jomofisher.cmakeserver.model.Messages10.internal_static_HandshakeMessage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jomofisher.cmakeserver.model.Messages10.internal_static_HandshakeMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jomofisher.cmakeserver.model.HandshakeMessage.class, com.jomofisher.cmakeserver.model.HandshakeMessage.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object type_;
  /**
   * <code>optional string type = 1;</code>
   */
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>optional string type = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COOKIE_FIELD_NUMBER = 2;
  private volatile java.lang.Object cookie_;
  /**
   * <code>optional string cookie = 2;</code>
   */
  public java.lang.String getCookie() {
    java.lang.Object ref = cookie_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cookie_ = s;
      return s;
    }
  }
  /**
   * <code>optional string cookie = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCookieBytes() {
    java.lang.Object ref = cookie_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cookie_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROTOCOLVERSION_FIELD_NUMBER = 3;
  private com.jomofisher.cmakeserver.model.ProtocolVersion protocolVersion_;
  /**
   * <code>optional .ProtocolVersion protocolVersion = 3;</code>
   */
  public boolean hasProtocolVersion() {
    return protocolVersion_ != null;
  }
  /**
   * <code>optional .ProtocolVersion protocolVersion = 3;</code>
   */
  public com.jomofisher.cmakeserver.model.ProtocolVersion getProtocolVersion() {
    return protocolVersion_ == null ? com.jomofisher.cmakeserver.model.ProtocolVersion.getDefaultInstance() : protocolVersion_;
  }
  /**
   * <code>optional .ProtocolVersion protocolVersion = 3;</code>
   */
  public com.jomofisher.cmakeserver.model.ProtocolVersionOrBuilder getProtocolVersionOrBuilder() {
    return getProtocolVersion();
  }

  public static final int SOURCEDIRECTORY_FIELD_NUMBER = 4;
  private volatile java.lang.Object sourceDirectory_;
  /**
   * <code>optional string sourceDirectory = 4;</code>
   */
  public java.lang.String getSourceDirectory() {
    java.lang.Object ref = sourceDirectory_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceDirectory_ = s;
      return s;
    }
  }
  /**
   * <code>optional string sourceDirectory = 4;</code>
   */
  public com.google.protobuf.ByteString
      getSourceDirectoryBytes() {
    java.lang.Object ref = sourceDirectory_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceDirectory_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BUILDDIRECTORY_FIELD_NUMBER = 5;
  private volatile java.lang.Object buildDirectory_;
  /**
   * <code>optional string buildDirectory = 5;</code>
   */
  public java.lang.String getBuildDirectory() {
    java.lang.Object ref = buildDirectory_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      buildDirectory_ = s;
      return s;
    }
  }
  /**
   * <code>optional string buildDirectory = 5;</code>
   */
  public com.google.protobuf.ByteString
      getBuildDirectoryBytes() {
    java.lang.Object ref = buildDirectory_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      buildDirectory_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENERATOR_FIELD_NUMBER = 6;
  private volatile java.lang.Object generator_;
  /**
   * <code>optional string generator = 6;</code>
   */
  public java.lang.String getGenerator() {
    java.lang.Object ref = generator_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      generator_ = s;
      return s;
    }
  }
  /**
   * <code>optional string generator = 6;</code>
   */
  public com.google.protobuf.ByteString
      getGeneratorBytes() {
    java.lang.Object ref = generator_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      generator_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
    }
    if (!getCookieBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cookie_);
    }
    if (protocolVersion_ != null) {
      output.writeMessage(3, getProtocolVersion());
    }
    if (!getSourceDirectoryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sourceDirectory_);
    }
    if (!getBuildDirectoryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, buildDirectory_);
    }
    if (!getGeneratorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, generator_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
    }
    if (!getCookieBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cookie_);
    }
    if (protocolVersion_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getProtocolVersion());
    }
    if (!getSourceDirectoryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sourceDirectory_);
    }
    if (!getBuildDirectoryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, buildDirectory_);
    }
    if (!getGeneratorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, generator_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.jomofisher.cmakeserver.model.HandshakeMessage)) {
      return super.equals(obj);
    }
    com.jomofisher.cmakeserver.model.HandshakeMessage other = (com.jomofisher.cmakeserver.model.HandshakeMessage) obj;

    boolean result = true;
    result = result && getType()
        .equals(other.getType());
    result = result && getCookie()
        .equals(other.getCookie());
    result = result && (hasProtocolVersion() == other.hasProtocolVersion());
    if (hasProtocolVersion()) {
      result = result && getProtocolVersion()
          .equals(other.getProtocolVersion());
    }
    result = result && getSourceDirectory()
        .equals(other.getSourceDirectory());
    result = result && getBuildDirectory()
        .equals(other.getBuildDirectory());
    result = result && getGenerator()
        .equals(other.getGenerator());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + COOKIE_FIELD_NUMBER;
    hash = (53 * hash) + getCookie().hashCode();
    if (hasProtocolVersion()) {
      hash = (37 * hash) + PROTOCOLVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getProtocolVersion().hashCode();
    }
    hash = (37 * hash) + SOURCEDIRECTORY_FIELD_NUMBER;
    hash = (53 * hash) + getSourceDirectory().hashCode();
    hash = (37 * hash) + BUILDDIRECTORY_FIELD_NUMBER;
    hash = (53 * hash) + getBuildDirectory().hashCode();
    hash = (37 * hash) + GENERATOR_FIELD_NUMBER;
    hash = (53 * hash) + getGenerator().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.jomofisher.cmakeserver.model.HandshakeMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jomofisher.cmakeserver.model.HandshakeMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.HandshakeMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jomofisher.cmakeserver.model.HandshakeMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.HandshakeMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jomofisher.cmakeserver.model.HandshakeMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.HandshakeMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.jomofisher.cmakeserver.model.HandshakeMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.HandshakeMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jomofisher.cmakeserver.model.HandshakeMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.jomofisher.cmakeserver.model.HandshakeMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code HandshakeMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:HandshakeMessage)
      com.jomofisher.cmakeserver.model.HandshakeMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jomofisher.cmakeserver.model.Messages10.internal_static_HandshakeMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jomofisher.cmakeserver.model.Messages10.internal_static_HandshakeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jomofisher.cmakeserver.model.HandshakeMessage.class, com.jomofisher.cmakeserver.model.HandshakeMessage.Builder.class);
    }

    // Construct using com.jomofisher.cmakeserver.model.HandshakeMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      type_ = "";

      cookie_ = "";

      if (protocolVersionBuilder_ == null) {
        protocolVersion_ = null;
      } else {
        protocolVersion_ = null;
        protocolVersionBuilder_ = null;
      }
      sourceDirectory_ = "";

      buildDirectory_ = "";

      generator_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jomofisher.cmakeserver.model.Messages10.internal_static_HandshakeMessage_descriptor;
    }

    public com.jomofisher.cmakeserver.model.HandshakeMessage getDefaultInstanceForType() {
      return com.jomofisher.cmakeserver.model.HandshakeMessage.getDefaultInstance();
    }

    public com.jomofisher.cmakeserver.model.HandshakeMessage build() {
      com.jomofisher.cmakeserver.model.HandshakeMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.jomofisher.cmakeserver.model.HandshakeMessage buildPartial() {
      com.jomofisher.cmakeserver.model.HandshakeMessage result = new com.jomofisher.cmakeserver.model.HandshakeMessage(this);
      result.type_ = type_;
      result.cookie_ = cookie_;
      if (protocolVersionBuilder_ == null) {
        result.protocolVersion_ = protocolVersion_;
      } else {
        result.protocolVersion_ = protocolVersionBuilder_.build();
      }
      result.sourceDirectory_ = sourceDirectory_;
      result.buildDirectory_ = buildDirectory_;
      result.generator_ = generator_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jomofisher.cmakeserver.model.HandshakeMessage) {
        return mergeFrom((com.jomofisher.cmakeserver.model.HandshakeMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jomofisher.cmakeserver.model.HandshakeMessage other) {
      if (other == com.jomofisher.cmakeserver.model.HandshakeMessage.getDefaultInstance()) return this;
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (!other.getCookie().isEmpty()) {
        cookie_ = other.cookie_;
        onChanged();
      }
      if (other.hasProtocolVersion()) {
        mergeProtocolVersion(other.getProtocolVersion());
      }
      if (!other.getSourceDirectory().isEmpty()) {
        sourceDirectory_ = other.sourceDirectory_;
        onChanged();
      }
      if (!other.getBuildDirectory().isEmpty()) {
        buildDirectory_ = other.buildDirectory_;
        onChanged();
      }
      if (!other.getGenerator().isEmpty()) {
        generator_ = other.generator_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.jomofisher.cmakeserver.model.HandshakeMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.jomofisher.cmakeserver.model.HandshakeMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>optional string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string type = 1;</code>
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string type = 1;</code>
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>optional string type = 1;</code>
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cookie_ = "";
    /**
     * <code>optional string cookie = 2;</code>
     */
    public java.lang.String getCookie() {
      java.lang.Object ref = cookie_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cookie_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string cookie = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCookieBytes() {
      java.lang.Object ref = cookie_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cookie_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string cookie = 2;</code>
     */
    public Builder setCookie(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cookie_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string cookie = 2;</code>
     */
    public Builder clearCookie() {
      
      cookie_ = getDefaultInstance().getCookie();
      onChanged();
      return this;
    }
    /**
     * <code>optional string cookie = 2;</code>
     */
    public Builder setCookieBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cookie_ = value;
      onChanged();
      return this;
    }

    private com.jomofisher.cmakeserver.model.ProtocolVersion protocolVersion_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.jomofisher.cmakeserver.model.ProtocolVersion, com.jomofisher.cmakeserver.model.ProtocolVersion.Builder, com.jomofisher.cmakeserver.model.ProtocolVersionOrBuilder> protocolVersionBuilder_;
    /**
     * <code>optional .ProtocolVersion protocolVersion = 3;</code>
     */
    public boolean hasProtocolVersion() {
      return protocolVersionBuilder_ != null || protocolVersion_ != null;
    }
    /**
     * <code>optional .ProtocolVersion protocolVersion = 3;</code>
     */
    public com.jomofisher.cmakeserver.model.ProtocolVersion getProtocolVersion() {
      if (protocolVersionBuilder_ == null) {
        return protocolVersion_ == null ? com.jomofisher.cmakeserver.model.ProtocolVersion.getDefaultInstance() : protocolVersion_;
      } else {
        return protocolVersionBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .ProtocolVersion protocolVersion = 3;</code>
     */
    public Builder setProtocolVersion(com.jomofisher.cmakeserver.model.ProtocolVersion value) {
      if (protocolVersionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        protocolVersion_ = value;
        onChanged();
      } else {
        protocolVersionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .ProtocolVersion protocolVersion = 3;</code>
     */
    public Builder setProtocolVersion(
        com.jomofisher.cmakeserver.model.ProtocolVersion.Builder builderForValue) {
      if (protocolVersionBuilder_ == null) {
        protocolVersion_ = builderForValue.build();
        onChanged();
      } else {
        protocolVersionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .ProtocolVersion protocolVersion = 3;</code>
     */
    public Builder mergeProtocolVersion(com.jomofisher.cmakeserver.model.ProtocolVersion value) {
      if (protocolVersionBuilder_ == null) {
        if (protocolVersion_ != null) {
          protocolVersion_ =
            com.jomofisher.cmakeserver.model.ProtocolVersion.newBuilder(protocolVersion_).mergeFrom(value).buildPartial();
        } else {
          protocolVersion_ = value;
        }
        onChanged();
      } else {
        protocolVersionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .ProtocolVersion protocolVersion = 3;</code>
     */
    public Builder clearProtocolVersion() {
      if (protocolVersionBuilder_ == null) {
        protocolVersion_ = null;
        onChanged();
      } else {
        protocolVersion_ = null;
        protocolVersionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .ProtocolVersion protocolVersion = 3;</code>
     */
    public com.jomofisher.cmakeserver.model.ProtocolVersion.Builder getProtocolVersionBuilder() {
      
      onChanged();
      return getProtocolVersionFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .ProtocolVersion protocolVersion = 3;</code>
     */
    public com.jomofisher.cmakeserver.model.ProtocolVersionOrBuilder getProtocolVersionOrBuilder() {
      if (protocolVersionBuilder_ != null) {
        return protocolVersionBuilder_.getMessageOrBuilder();
      } else {
        return protocolVersion_ == null ?
            com.jomofisher.cmakeserver.model.ProtocolVersion.getDefaultInstance() : protocolVersion_;
      }
    }
    /**
     * <code>optional .ProtocolVersion protocolVersion = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.jomofisher.cmakeserver.model.ProtocolVersion, com.jomofisher.cmakeserver.model.ProtocolVersion.Builder, com.jomofisher.cmakeserver.model.ProtocolVersionOrBuilder> 
        getProtocolVersionFieldBuilder() {
      if (protocolVersionBuilder_ == null) {
        protocolVersionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.jomofisher.cmakeserver.model.ProtocolVersion, com.jomofisher.cmakeserver.model.ProtocolVersion.Builder, com.jomofisher.cmakeserver.model.ProtocolVersionOrBuilder>(
                getProtocolVersion(),
                getParentForChildren(),
                isClean());
        protocolVersion_ = null;
      }
      return protocolVersionBuilder_;
    }

    private java.lang.Object sourceDirectory_ = "";
    /**
     * <code>optional string sourceDirectory = 4;</code>
     */
    public java.lang.String getSourceDirectory() {
      java.lang.Object ref = sourceDirectory_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceDirectory_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sourceDirectory = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSourceDirectoryBytes() {
      java.lang.Object ref = sourceDirectory_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceDirectory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sourceDirectory = 4;</code>
     */
    public Builder setSourceDirectory(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceDirectory_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sourceDirectory = 4;</code>
     */
    public Builder clearSourceDirectory() {
      
      sourceDirectory_ = getDefaultInstance().getSourceDirectory();
      onChanged();
      return this;
    }
    /**
     * <code>optional string sourceDirectory = 4;</code>
     */
    public Builder setSourceDirectoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceDirectory_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object buildDirectory_ = "";
    /**
     * <code>optional string buildDirectory = 5;</code>
     */
    public java.lang.String getBuildDirectory() {
      java.lang.Object ref = buildDirectory_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buildDirectory_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string buildDirectory = 5;</code>
     */
    public com.google.protobuf.ByteString
        getBuildDirectoryBytes() {
      java.lang.Object ref = buildDirectory_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buildDirectory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string buildDirectory = 5;</code>
     */
    public Builder setBuildDirectory(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      buildDirectory_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string buildDirectory = 5;</code>
     */
    public Builder clearBuildDirectory() {
      
      buildDirectory_ = getDefaultInstance().getBuildDirectory();
      onChanged();
      return this;
    }
    /**
     * <code>optional string buildDirectory = 5;</code>
     */
    public Builder setBuildDirectoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      buildDirectory_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object generator_ = "";
    /**
     * <code>optional string generator = 6;</code>
     */
    public java.lang.String getGenerator() {
      java.lang.Object ref = generator_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        generator_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string generator = 6;</code>
     */
    public com.google.protobuf.ByteString
        getGeneratorBytes() {
      java.lang.Object ref = generator_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        generator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string generator = 6;</code>
     */
    public Builder setGenerator(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      generator_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string generator = 6;</code>
     */
    public Builder clearGenerator() {
      
      generator_ = getDefaultInstance().getGenerator();
      onChanged();
      return this;
    }
    /**
     * <code>optional string generator = 6;</code>
     */
    public Builder setGeneratorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      generator_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:HandshakeMessage)
  }

  // @@protoc_insertion_point(class_scope:HandshakeMessage)
  private static final com.jomofisher.cmakeserver.model.HandshakeMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.jomofisher.cmakeserver.model.HandshakeMessage();
  }

  public static com.jomofisher.cmakeserver.model.HandshakeMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HandshakeMessage>
      PARSER = new com.google.protobuf.AbstractParser<HandshakeMessage>() {
    public HandshakeMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new HandshakeMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HandshakeMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HandshakeMessage> getParserForType() {
    return PARSER;
  }

  public com.jomofisher.cmakeserver.model.HandshakeMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

