// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.1.0.proto

package com.jomofisher.cmakeserver.model;

public interface IncludePathOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IncludePath)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool isSystem = 1;</code>
   */
  boolean getIsSystem();

  /**
   * <code>optional string path = 2;</code>
   */
  java.lang.String getPath();
  /**
   * <code>optional string path = 2;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();
}
