// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.1.0.proto

package com.jomofisher.cmakeserver.model;

public final class Messages10 {
  private Messages10() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TypeOfMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TypeOfMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfigureReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConfigureReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalSettingsReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GlobalSettingsReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Capabilities_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Capabilities_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Generator_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Generator_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Version_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Version_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HandshakeReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HandshakeReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HandshakeMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HandshakeMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtocolVersion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtocolVersion_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CodeModelReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CodeModelReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Configuration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Configuration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Project_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Project_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Target_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Target_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileGroup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IncludePath_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IncludePath_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ComputeReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ComputeReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProgressReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProgressReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfigureMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConfigureMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022messages.1.0.proto\"\035\n\rTypeOfMessage\022\014\n" +
      "\004type\030\001 \001(\t\"A\n\016ConfigureReply\022\014\n\004type\030\001 " +
      "\001(\t\022\016\n\006cookie\030\002 \001(\t\022\021\n\tinReplyTo\030\003 \001(\t\"\337" +
      "\002\n\023GlobalSettingsReply\022\014\n\004type\030\001 \001(\t\022\016\n\006" +
      "cookie\030\002 \001(\t\022\021\n\tinReplyTo\030\003 \001(\t\022\026\n\016build" +
      "Directory\030\004 \001(\t\022\027\n\017checkSystemVars\030\005 \001(\010" +
      "\022\023\n\013debugOutput\030\006 \001(\010\022\026\n\016extraGenerator\030" +
      "\007 \001(\t\022\021\n\tgenerator\030\010 \001(\t\022\027\n\017sourceDirect" +
      "ory\030\t \001(\t\022\r\n\005trace\030\n \001(\010\022\023\n\013traceExpand\030" +
      "\013 \001(\010\022\031\n\021warnUninitialized\030\014 \001(\010\022\022\n\nwarn",
      "Unused\030\r \001(\010\022\025\n\rwarnUnusedCli\030\016 \001(\010\022#\n\014c" +
      "apabilities\030\017 \001(\0132\r.Capabilities\"]\n\014Capa" +
      "bilities\022\036\n\ngenerators\030\001 \003(\0132\n.Generator" +
      "\022\022\n\nserverMode\030\002 \001(\010\022\031\n\007version\030\003 \001(\0132\010." +
      "Version\"c\n\tGenerator\022\014\n\004name\030\001 \001(\t\022\027\n\017pl" +
      "atformSupport\030\002 \001(\010\022\026\n\016toolsetSupport\030\003 " +
      "\001(\010\022\027\n\017extraGenerators\030\004 \003(\t\"g\n\007Version\022" +
      "\017\n\007isDirty\030\001 \001(\010\022\r\n\005major\030\002 \001(\005\022\r\n\005minor" +
      "\030\003 \001(\005\022\r\n\005patch\030\004 \001(\005\022\016\n\006string\030\005 \001(\t\022\016\n" +
      "\006suffix\030\006 \001(\t\"A\n\016HandshakeReply\022\014\n\004type\030",
      "\001 \001(\t\022\016\n\006cookie\030\002 \001(\t\022\021\n\tinReplyTo\030\003 \001(\t" +
      "\"\237\001\n\020HandshakeMessage\022\014\n\004type\030\001 \001(\t\022\016\n\006c" +
      "ookie\030\002 \001(\t\022)\n\017protocolVersion\030\003 \001(\0132\020.P" +
      "rotocolVersion\022\027\n\017sourceDirectory\030\004 \001(\t\022" +
      "\026\n\016buildDirectory\030\005 \001(\t\022\021\n\tgenerator\030\006 \001" +
      "(\t\"G\n\017ProtocolVersion\022\026\n\016isExperimental\030" +
      "\001 \001(\010\022\r\n\005major\030\002 \001(\005\022\r\n\005minor\030\003 \001(\005\"i\n\016C" +
      "odeModelReply\022\014\n\004type\030\001 \001(\t\022\016\n\006cookie\030\002 " +
      "\001(\t\022\021\n\tinReplyTo\030\003 \001(\t\022&\n\016configurations" +
      "\030\004 \003(\0132\016.Configuration\"9\n\rConfiguration\022",
      "\014\n\004name\030\001 \001(\t\022\032\n\010projects\030\002 \003(\0132\010.Projec" +
      "t\"b\n\007Project\022\026\n\016buildDirectory\030\001 \001(\t\022\014\n\004" +
      "name\030\002 \001(\t\022\027\n\017sourceDirectory\030\003 \001(\t\022\030\n\007t" +
      "argets\030\004 \003(\0132\007.Target\"\355\001\n\006Target\022\021\n\tarti" +
      "facts\030\001 \003(\t\022\026\n\016buildDirectory\030\002 \001(\t\022\036\n\nf" +
      "ileGroups\030\003 \003(\0132\n.FileGroup\022\020\n\010fullName\030" +
      "\004 \001(\t\022\025\n\rlinkLibraries\030\005 \001(\t\022\026\n\016linkerLa" +
      "nguage\030\006 \001(\t\022\014\n\004name\030\007 \001(\t\022\027\n\017sourceDire" +
      "ctory\030\010 \001(\t\022\014\n\004type\030\t \001(\t\022\021\n\tlinkFlags\030\n" +
      " \001(\t\022\017\n\007sysroot\030\013 \001(\t\"\215\001\n\tFileGroup\022\024\n\014c",
      "ompileFlags\030\001 \001(\t\022\023\n\013isGenerated\030\002 \001(\010\022\020" +
      "\n\010language\030\003 \001(\t\022\017\n\007sources\030\004 \003(\t\022\017\n\007def" +
      "ines\030\005 \003(\t\022!\n\013includePath\030\006 \003(\0132\014.Includ" +
      "ePath\"-\n\013IncludePath\022\020\n\010isSystem\030\001 \001(\010\022\014" +
      "\n\004path\030\002 \001(\t\"?\n\014ComputeReply\022\014\n\004type\030\001 \001" +
      "(\t\022\016\n\006cookie\030\002 \001(\t\022\021\n\tinReplyTo\030\003 \001(\t\"=\n" +
      "\nHelloReply\022\014\n\004type\030\001 \001(\t\022\016\n\006cookie\030\002 \001(" +
      "\t\022\021\n\tinReplyTo\030\003 \001(\t\"_\n\014MessageReply\022\014\n\004" +
      "type\030\001 \001(\t\022\016\n\006cookie\030\002 \001(\t\022\021\n\tinReplyTo\030" +
      "\003 \001(\t\022\017\n\007message\030\004 \001(\t\022\r\n\005title\030\005 \001(\t\"\304\001",
      "\n\rProgressReply\022\014\n\004type\030\001 \001(\t\022\016\n\006cookie\030" +
      "\002 \001(\t\022\021\n\tinReplyTo\030\003 \001(\t\022\017\n\007message\030\004 \001(" +
      "\t\022\r\n\005title\030\005 \001(\t\022\027\n\017progressCurrent\030\006 \001(" +
      "\005\022\027\n\017progressMaximum\030\007 \001(\005\022\027\n\017progressMe" +
      "ssage\030\010 \001(\t\022\027\n\017progressMinimum\030\t \001(\005\"8\n\020" +
      "ConfigureMessage\022\014\n\004type\030\001 \001(\t\022\026\n\016cacheA" +
      "rguments\030\002 \003(\tB$\n com.jomofisher.cmakese" +
      "rver.modelP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TypeOfMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TypeOfMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TypeOfMessage_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_ConfigureReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ConfigureReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConfigureReply_descriptor,
        new java.lang.String[] { "Type", "Cookie", "InReplyTo", });
    internal_static_GlobalSettingsReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GlobalSettingsReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GlobalSettingsReply_descriptor,
        new java.lang.String[] { "Type", "Cookie", "InReplyTo", "BuildDirectory", "CheckSystemVars", "DebugOutput", "ExtraGenerator", "Generator", "SourceDirectory", "Trace", "TraceExpand", "WarnUninitialized", "WarnUnused", "WarnUnusedCli", "Capabilities", });
    internal_static_Capabilities_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Capabilities_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Capabilities_descriptor,
        new java.lang.String[] { "Generators", "ServerMode", "Version", });
    internal_static_Generator_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Generator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Generator_descriptor,
        new java.lang.String[] { "Name", "PlatformSupport", "ToolsetSupport", "ExtraGenerators", });
    internal_static_Version_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Version_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Version_descriptor,
        new java.lang.String[] { "IsDirty", "Major", "Minor", "Patch", "String", "Suffix", });
    internal_static_HandshakeReply_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_HandshakeReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HandshakeReply_descriptor,
        new java.lang.String[] { "Type", "Cookie", "InReplyTo", });
    internal_static_HandshakeMessage_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_HandshakeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HandshakeMessage_descriptor,
        new java.lang.String[] { "Type", "Cookie", "ProtocolVersion", "SourceDirectory", "BuildDirectory", "Generator", });
    internal_static_ProtocolVersion_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_ProtocolVersion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtocolVersion_descriptor,
        new java.lang.String[] { "IsExperimental", "Major", "Minor", });
    internal_static_CodeModelReply_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_CodeModelReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CodeModelReply_descriptor,
        new java.lang.String[] { "Type", "Cookie", "InReplyTo", "Configurations", });
    internal_static_Configuration_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_Configuration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Configuration_descriptor,
        new java.lang.String[] { "Name", "Projects", });
    internal_static_Project_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_Project_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Project_descriptor,
        new java.lang.String[] { "BuildDirectory", "Name", "SourceDirectory", "Targets", });
    internal_static_Target_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_Target_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Target_descriptor,
        new java.lang.String[] { "Artifacts", "BuildDirectory", "FileGroups", "FullName", "LinkLibraries", "LinkerLanguage", "Name", "SourceDirectory", "Type", "LinkFlags", "Sysroot", });
    internal_static_FileGroup_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_FileGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileGroup_descriptor,
        new java.lang.String[] { "CompileFlags", "IsGenerated", "Language", "Sources", "Defines", "IncludePath", });
    internal_static_IncludePath_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_IncludePath_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IncludePath_descriptor,
        new java.lang.String[] { "IsSystem", "Path", });
    internal_static_ComputeReply_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_ComputeReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ComputeReply_descriptor,
        new java.lang.String[] { "Type", "Cookie", "InReplyTo", });
    internal_static_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloReply_descriptor,
        new java.lang.String[] { "Type", "Cookie", "InReplyTo", });
    internal_static_MessageReply_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_MessageReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageReply_descriptor,
        new java.lang.String[] { "Type", "Cookie", "InReplyTo", "Message", "Title", });
    internal_static_ProgressReply_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_ProgressReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProgressReply_descriptor,
        new java.lang.String[] { "Type", "Cookie", "InReplyTo", "Message", "Title", "ProgressCurrent", "ProgressMaximum", "ProgressMessage", "ProgressMinimum", });
    internal_static_ConfigureMessage_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_ConfigureMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConfigureMessage_descriptor,
        new java.lang.String[] { "Type", "CacheArguments", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
