// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.1.0.proto

package com.jomofisher.cmakeserver.model;

public interface MessageReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string type = 1;</code>
   */
  java.lang.String getType();
  /**
   * <code>optional string type = 1;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>optional string cookie = 2;</code>
   */
  java.lang.String getCookie();
  /**
   * <code>optional string cookie = 2;</code>
   */
  com.google.protobuf.ByteString
      getCookieBytes();

  /**
   * <code>optional string inReplyTo = 3;</code>
   */
  java.lang.String getInReplyTo();
  /**
   * <code>optional string inReplyTo = 3;</code>
   */
  com.google.protobuf.ByteString
      getInReplyToBytes();

  /**
   * <code>optional string message = 4;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 4;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>optional string title = 5;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>optional string title = 5;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();
}
