// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.1.0.proto

package com.jomofisher.cmakeserver.model;

/**
 * Protobuf type {@code ProgressReply}
 */
public  final class ProgressReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ProgressReply)
    ProgressReplyOrBuilder {
  // Use ProgressReply.newBuilder() to construct.
  private ProgressReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProgressReply() {
    type_ = "";
    cookie_ = "";
    inReplyTo_ = "";
    message_ = "";
    title_ = "";
    progressCurrent_ = 0;
    progressMaximum_ = 0;
    progressMessage_ = "";
    progressMinimum_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ProgressReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            cookie_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            inReplyTo_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 48: {

            progressCurrent_ = input.readInt32();
            break;
          }
          case 56: {

            progressMaximum_ = input.readInt32();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            progressMessage_ = s;
            break;
          }
          case 72: {

            progressMinimum_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jomofisher.cmakeserver.model.Messages10.internal_static_ProgressReply_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jomofisher.cmakeserver.model.Messages10.internal_static_ProgressReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jomofisher.cmakeserver.model.ProgressReply.class, com.jomofisher.cmakeserver.model.ProgressReply.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object type_;
  /**
   * <code>optional string type = 1;</code>
   */
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>optional string type = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COOKIE_FIELD_NUMBER = 2;
  private volatile java.lang.Object cookie_;
  /**
   * <code>optional string cookie = 2;</code>
   */
  public java.lang.String getCookie() {
    java.lang.Object ref = cookie_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cookie_ = s;
      return s;
    }
  }
  /**
   * <code>optional string cookie = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCookieBytes() {
    java.lang.Object ref = cookie_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cookie_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INREPLYTO_FIELD_NUMBER = 3;
  private volatile java.lang.Object inReplyTo_;
  /**
   * <code>optional string inReplyTo = 3;</code>
   */
  public java.lang.String getInReplyTo() {
    java.lang.Object ref = inReplyTo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      inReplyTo_ = s;
      return s;
    }
  }
  /**
   * <code>optional string inReplyTo = 3;</code>
   */
  public com.google.protobuf.ByteString
      getInReplyToBytes() {
    java.lang.Object ref = inReplyTo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      inReplyTo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 4;
  private volatile java.lang.Object message_;
  /**
   * <code>optional string message = 4;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>optional string message = 4;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TITLE_FIELD_NUMBER = 5;
  private volatile java.lang.Object title_;
  /**
   * <code>optional string title = 5;</code>
   */
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>optional string title = 5;</code>
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROGRESSCURRENT_FIELD_NUMBER = 6;
  private int progressCurrent_;
  /**
   * <code>optional int32 progressCurrent = 6;</code>
   */
  public int getProgressCurrent() {
    return progressCurrent_;
  }

  public static final int PROGRESSMAXIMUM_FIELD_NUMBER = 7;
  private int progressMaximum_;
  /**
   * <code>optional int32 progressMaximum = 7;</code>
   */
  public int getProgressMaximum() {
    return progressMaximum_;
  }

  public static final int PROGRESSMESSAGE_FIELD_NUMBER = 8;
  private volatile java.lang.Object progressMessage_;
  /**
   * <code>optional string progressMessage = 8;</code>
   */
  public java.lang.String getProgressMessage() {
    java.lang.Object ref = progressMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      progressMessage_ = s;
      return s;
    }
  }
  /**
   * <code>optional string progressMessage = 8;</code>
   */
  public com.google.protobuf.ByteString
      getProgressMessageBytes() {
    java.lang.Object ref = progressMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      progressMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROGRESSMINIMUM_FIELD_NUMBER = 9;
  private int progressMinimum_;
  /**
   * <code>optional int32 progressMinimum = 9;</code>
   */
  public int getProgressMinimum() {
    return progressMinimum_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
    }
    if (!getCookieBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cookie_);
    }
    if (!getInReplyToBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, inReplyTo_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, message_);
    }
    if (!getTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, title_);
    }
    if (progressCurrent_ != 0) {
      output.writeInt32(6, progressCurrent_);
    }
    if (progressMaximum_ != 0) {
      output.writeInt32(7, progressMaximum_);
    }
    if (!getProgressMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, progressMessage_);
    }
    if (progressMinimum_ != 0) {
      output.writeInt32(9, progressMinimum_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
    }
    if (!getCookieBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cookie_);
    }
    if (!getInReplyToBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, inReplyTo_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, message_);
    }
    if (!getTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, title_);
    }
    if (progressCurrent_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, progressCurrent_);
    }
    if (progressMaximum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, progressMaximum_);
    }
    if (!getProgressMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, progressMessage_);
    }
    if (progressMinimum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, progressMinimum_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.jomofisher.cmakeserver.model.ProgressReply)) {
      return super.equals(obj);
    }
    com.jomofisher.cmakeserver.model.ProgressReply other = (com.jomofisher.cmakeserver.model.ProgressReply) obj;

    boolean result = true;
    result = result && getType()
        .equals(other.getType());
    result = result && getCookie()
        .equals(other.getCookie());
    result = result && getInReplyTo()
        .equals(other.getInReplyTo());
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && getTitle()
        .equals(other.getTitle());
    result = result && (getProgressCurrent()
        == other.getProgressCurrent());
    result = result && (getProgressMaximum()
        == other.getProgressMaximum());
    result = result && getProgressMessage()
        .equals(other.getProgressMessage());
    result = result && (getProgressMinimum()
        == other.getProgressMinimum());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + COOKIE_FIELD_NUMBER;
    hash = (53 * hash) + getCookie().hashCode();
    hash = (37 * hash) + INREPLYTO_FIELD_NUMBER;
    hash = (53 * hash) + getInReplyTo().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + PROGRESSCURRENT_FIELD_NUMBER;
    hash = (53 * hash) + getProgressCurrent();
    hash = (37 * hash) + PROGRESSMAXIMUM_FIELD_NUMBER;
    hash = (53 * hash) + getProgressMaximum();
    hash = (37 * hash) + PROGRESSMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getProgressMessage().hashCode();
    hash = (37 * hash) + PROGRESSMINIMUM_FIELD_NUMBER;
    hash = (53 * hash) + getProgressMinimum();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.jomofisher.cmakeserver.model.ProgressReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jomofisher.cmakeserver.model.ProgressReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.ProgressReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jomofisher.cmakeserver.model.ProgressReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.ProgressReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jomofisher.cmakeserver.model.ProgressReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.ProgressReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.jomofisher.cmakeserver.model.ProgressReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.ProgressReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jomofisher.cmakeserver.model.ProgressReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.jomofisher.cmakeserver.model.ProgressReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ProgressReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ProgressReply)
      com.jomofisher.cmakeserver.model.ProgressReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jomofisher.cmakeserver.model.Messages10.internal_static_ProgressReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jomofisher.cmakeserver.model.Messages10.internal_static_ProgressReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jomofisher.cmakeserver.model.ProgressReply.class, com.jomofisher.cmakeserver.model.ProgressReply.Builder.class);
    }

    // Construct using com.jomofisher.cmakeserver.model.ProgressReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      type_ = "";

      cookie_ = "";

      inReplyTo_ = "";

      message_ = "";

      title_ = "";

      progressCurrent_ = 0;

      progressMaximum_ = 0;

      progressMessage_ = "";

      progressMinimum_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jomofisher.cmakeserver.model.Messages10.internal_static_ProgressReply_descriptor;
    }

    public com.jomofisher.cmakeserver.model.ProgressReply getDefaultInstanceForType() {
      return com.jomofisher.cmakeserver.model.ProgressReply.getDefaultInstance();
    }

    public com.jomofisher.cmakeserver.model.ProgressReply build() {
      com.jomofisher.cmakeserver.model.ProgressReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.jomofisher.cmakeserver.model.ProgressReply buildPartial() {
      com.jomofisher.cmakeserver.model.ProgressReply result = new com.jomofisher.cmakeserver.model.ProgressReply(this);
      result.type_ = type_;
      result.cookie_ = cookie_;
      result.inReplyTo_ = inReplyTo_;
      result.message_ = message_;
      result.title_ = title_;
      result.progressCurrent_ = progressCurrent_;
      result.progressMaximum_ = progressMaximum_;
      result.progressMessage_ = progressMessage_;
      result.progressMinimum_ = progressMinimum_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jomofisher.cmakeserver.model.ProgressReply) {
        return mergeFrom((com.jomofisher.cmakeserver.model.ProgressReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jomofisher.cmakeserver.model.ProgressReply other) {
      if (other == com.jomofisher.cmakeserver.model.ProgressReply.getDefaultInstance()) return this;
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (!other.getCookie().isEmpty()) {
        cookie_ = other.cookie_;
        onChanged();
      }
      if (!other.getInReplyTo().isEmpty()) {
        inReplyTo_ = other.inReplyTo_;
        onChanged();
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (other.getProgressCurrent() != 0) {
        setProgressCurrent(other.getProgressCurrent());
      }
      if (other.getProgressMaximum() != 0) {
        setProgressMaximum(other.getProgressMaximum());
      }
      if (!other.getProgressMessage().isEmpty()) {
        progressMessage_ = other.progressMessage_;
        onChanged();
      }
      if (other.getProgressMinimum() != 0) {
        setProgressMinimum(other.getProgressMinimum());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.jomofisher.cmakeserver.model.ProgressReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.jomofisher.cmakeserver.model.ProgressReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>optional string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string type = 1;</code>
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string type = 1;</code>
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>optional string type = 1;</code>
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cookie_ = "";
    /**
     * <code>optional string cookie = 2;</code>
     */
    public java.lang.String getCookie() {
      java.lang.Object ref = cookie_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cookie_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string cookie = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCookieBytes() {
      java.lang.Object ref = cookie_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cookie_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string cookie = 2;</code>
     */
    public Builder setCookie(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cookie_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string cookie = 2;</code>
     */
    public Builder clearCookie() {
      
      cookie_ = getDefaultInstance().getCookie();
      onChanged();
      return this;
    }
    /**
     * <code>optional string cookie = 2;</code>
     */
    public Builder setCookieBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cookie_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object inReplyTo_ = "";
    /**
     * <code>optional string inReplyTo = 3;</code>
     */
    public java.lang.String getInReplyTo() {
      java.lang.Object ref = inReplyTo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        inReplyTo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string inReplyTo = 3;</code>
     */
    public com.google.protobuf.ByteString
        getInReplyToBytes() {
      java.lang.Object ref = inReplyTo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        inReplyTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string inReplyTo = 3;</code>
     */
    public Builder setInReplyTo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      inReplyTo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string inReplyTo = 3;</code>
     */
    public Builder clearInReplyTo() {
      
      inReplyTo_ = getDefaultInstance().getInReplyTo();
      onChanged();
      return this;
    }
    /**
     * <code>optional string inReplyTo = 3;</code>
     */
    public Builder setInReplyToBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      inReplyTo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>optional string message = 4;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string message = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string message = 4;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string message = 4;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>optional string message = 4;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>optional string title = 5;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string title = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string title = 5;</code>
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string title = 5;</code>
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>optional string title = 5;</code>
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private int progressCurrent_ ;
    /**
     * <code>optional int32 progressCurrent = 6;</code>
     */
    public int getProgressCurrent() {
      return progressCurrent_;
    }
    /**
     * <code>optional int32 progressCurrent = 6;</code>
     */
    public Builder setProgressCurrent(int value) {
      
      progressCurrent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 progressCurrent = 6;</code>
     */
    public Builder clearProgressCurrent() {
      
      progressCurrent_ = 0;
      onChanged();
      return this;
    }

    private int progressMaximum_ ;
    /**
     * <code>optional int32 progressMaximum = 7;</code>
     */
    public int getProgressMaximum() {
      return progressMaximum_;
    }
    /**
     * <code>optional int32 progressMaximum = 7;</code>
     */
    public Builder setProgressMaximum(int value) {
      
      progressMaximum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 progressMaximum = 7;</code>
     */
    public Builder clearProgressMaximum() {
      
      progressMaximum_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object progressMessage_ = "";
    /**
     * <code>optional string progressMessage = 8;</code>
     */
    public java.lang.String getProgressMessage() {
      java.lang.Object ref = progressMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        progressMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string progressMessage = 8;</code>
     */
    public com.google.protobuf.ByteString
        getProgressMessageBytes() {
      java.lang.Object ref = progressMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        progressMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string progressMessage = 8;</code>
     */
    public Builder setProgressMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      progressMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string progressMessage = 8;</code>
     */
    public Builder clearProgressMessage() {
      
      progressMessage_ = getDefaultInstance().getProgressMessage();
      onChanged();
      return this;
    }
    /**
     * <code>optional string progressMessage = 8;</code>
     */
    public Builder setProgressMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      progressMessage_ = value;
      onChanged();
      return this;
    }

    private int progressMinimum_ ;
    /**
     * <code>optional int32 progressMinimum = 9;</code>
     */
    public int getProgressMinimum() {
      return progressMinimum_;
    }
    /**
     * <code>optional int32 progressMinimum = 9;</code>
     */
    public Builder setProgressMinimum(int value) {
      
      progressMinimum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 progressMinimum = 9;</code>
     */
    public Builder clearProgressMinimum() {
      
      progressMinimum_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:ProgressReply)
  }

  // @@protoc_insertion_point(class_scope:ProgressReply)
  private static final com.jomofisher.cmakeserver.model.ProgressReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.jomofisher.cmakeserver.model.ProgressReply();
  }

  public static com.jomofisher.cmakeserver.model.ProgressReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProgressReply>
      PARSER = new com.google.protobuf.AbstractParser<ProgressReply>() {
    public ProgressReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProgressReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProgressReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProgressReply> getParserForType() {
    return PARSER;
  }

  public com.jomofisher.cmakeserver.model.ProgressReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

