// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.1.0.proto

package com.jomofisher.cmakeserver.model;

/**
 * Protobuf type {@code Project}
 */
public  final class Project extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Project)
    ProjectOrBuilder {
  // Use Project.newBuilder() to construct.
  private Project(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Project() {
    buildDirectory_ = "";
    name_ = "";
    sourceDirectory_ = "";
    targets_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Project(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            buildDirectory_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            sourceDirectory_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              targets_ = new java.util.ArrayList<com.jomofisher.cmakeserver.model.Target>();
              mutable_bitField0_ |= 0x00000008;
            }
            targets_.add(
                input.readMessage(com.jomofisher.cmakeserver.model.Target.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        targets_ = java.util.Collections.unmodifiableList(targets_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jomofisher.cmakeserver.model.Messages10.internal_static_Project_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jomofisher.cmakeserver.model.Messages10.internal_static_Project_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jomofisher.cmakeserver.model.Project.class, com.jomofisher.cmakeserver.model.Project.Builder.class);
  }

  private int bitField0_;
  public static final int BUILDDIRECTORY_FIELD_NUMBER = 1;
  private volatile java.lang.Object buildDirectory_;
  /**
   * <code>optional string buildDirectory = 1;</code>
   */
  public java.lang.String getBuildDirectory() {
    java.lang.Object ref = buildDirectory_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      buildDirectory_ = s;
      return s;
    }
  }
  /**
   * <code>optional string buildDirectory = 1;</code>
   */
  public com.google.protobuf.ByteString
      getBuildDirectoryBytes() {
    java.lang.Object ref = buildDirectory_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      buildDirectory_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCEDIRECTORY_FIELD_NUMBER = 3;
  private volatile java.lang.Object sourceDirectory_;
  /**
   * <code>optional string sourceDirectory = 3;</code>
   */
  public java.lang.String getSourceDirectory() {
    java.lang.Object ref = sourceDirectory_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceDirectory_ = s;
      return s;
    }
  }
  /**
   * <code>optional string sourceDirectory = 3;</code>
   */
  public com.google.protobuf.ByteString
      getSourceDirectoryBytes() {
    java.lang.Object ref = sourceDirectory_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceDirectory_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TARGETS_FIELD_NUMBER = 4;
  private java.util.List<com.jomofisher.cmakeserver.model.Target> targets_;
  /**
   * <code>repeated .Target targets = 4;</code>
   */
  public java.util.List<com.jomofisher.cmakeserver.model.Target> getTargetsList() {
    return targets_;
  }
  /**
   * <code>repeated .Target targets = 4;</code>
   */
  public java.util.List<? extends com.jomofisher.cmakeserver.model.TargetOrBuilder> 
      getTargetsOrBuilderList() {
    return targets_;
  }
  /**
   * <code>repeated .Target targets = 4;</code>
   */
  public int getTargetsCount() {
    return targets_.size();
  }
  /**
   * <code>repeated .Target targets = 4;</code>
   */
  public com.jomofisher.cmakeserver.model.Target getTargets(int index) {
    return targets_.get(index);
  }
  /**
   * <code>repeated .Target targets = 4;</code>
   */
  public com.jomofisher.cmakeserver.model.TargetOrBuilder getTargetsOrBuilder(
      int index) {
    return targets_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getBuildDirectoryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, buildDirectory_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!getSourceDirectoryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sourceDirectory_);
    }
    for (int i = 0; i < targets_.size(); i++) {
      output.writeMessage(4, targets_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBuildDirectoryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, buildDirectory_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!getSourceDirectoryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sourceDirectory_);
    }
    for (int i = 0; i < targets_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, targets_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.jomofisher.cmakeserver.model.Project)) {
      return super.equals(obj);
    }
    com.jomofisher.cmakeserver.model.Project other = (com.jomofisher.cmakeserver.model.Project) obj;

    boolean result = true;
    result = result && getBuildDirectory()
        .equals(other.getBuildDirectory());
    result = result && getName()
        .equals(other.getName());
    result = result && getSourceDirectory()
        .equals(other.getSourceDirectory());
    result = result && getTargetsList()
        .equals(other.getTargetsList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + BUILDDIRECTORY_FIELD_NUMBER;
    hash = (53 * hash) + getBuildDirectory().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + SOURCEDIRECTORY_FIELD_NUMBER;
    hash = (53 * hash) + getSourceDirectory().hashCode();
    if (getTargetsCount() > 0) {
      hash = (37 * hash) + TARGETS_FIELD_NUMBER;
      hash = (53 * hash) + getTargetsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.jomofisher.cmakeserver.model.Project parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jomofisher.cmakeserver.model.Project parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.Project parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jomofisher.cmakeserver.model.Project parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.Project parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jomofisher.cmakeserver.model.Project parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.Project parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.jomofisher.cmakeserver.model.Project parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jomofisher.cmakeserver.model.Project parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jomofisher.cmakeserver.model.Project parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.jomofisher.cmakeserver.model.Project prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Project}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Project)
      com.jomofisher.cmakeserver.model.ProjectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jomofisher.cmakeserver.model.Messages10.internal_static_Project_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jomofisher.cmakeserver.model.Messages10.internal_static_Project_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jomofisher.cmakeserver.model.Project.class, com.jomofisher.cmakeserver.model.Project.Builder.class);
    }

    // Construct using com.jomofisher.cmakeserver.model.Project.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTargetsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      buildDirectory_ = "";

      name_ = "";

      sourceDirectory_ = "";

      if (targetsBuilder_ == null) {
        targets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        targetsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jomofisher.cmakeserver.model.Messages10.internal_static_Project_descriptor;
    }

    public com.jomofisher.cmakeserver.model.Project getDefaultInstanceForType() {
      return com.jomofisher.cmakeserver.model.Project.getDefaultInstance();
    }

    public com.jomofisher.cmakeserver.model.Project build() {
      com.jomofisher.cmakeserver.model.Project result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.jomofisher.cmakeserver.model.Project buildPartial() {
      com.jomofisher.cmakeserver.model.Project result = new com.jomofisher.cmakeserver.model.Project(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.buildDirectory_ = buildDirectory_;
      result.name_ = name_;
      result.sourceDirectory_ = sourceDirectory_;
      if (targetsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          targets_ = java.util.Collections.unmodifiableList(targets_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.targets_ = targets_;
      } else {
        result.targets_ = targetsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jomofisher.cmakeserver.model.Project) {
        return mergeFrom((com.jomofisher.cmakeserver.model.Project)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jomofisher.cmakeserver.model.Project other) {
      if (other == com.jomofisher.cmakeserver.model.Project.getDefaultInstance()) return this;
      if (!other.getBuildDirectory().isEmpty()) {
        buildDirectory_ = other.buildDirectory_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getSourceDirectory().isEmpty()) {
        sourceDirectory_ = other.sourceDirectory_;
        onChanged();
      }
      if (targetsBuilder_ == null) {
        if (!other.targets_.isEmpty()) {
          if (targets_.isEmpty()) {
            targets_ = other.targets_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureTargetsIsMutable();
            targets_.addAll(other.targets_);
          }
          onChanged();
        }
      } else {
        if (!other.targets_.isEmpty()) {
          if (targetsBuilder_.isEmpty()) {
            targetsBuilder_.dispose();
            targetsBuilder_ = null;
            targets_ = other.targets_;
            bitField0_ = (bitField0_ & ~0x00000008);
            targetsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTargetsFieldBuilder() : null;
          } else {
            targetsBuilder_.addAllMessages(other.targets_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.jomofisher.cmakeserver.model.Project parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.jomofisher.cmakeserver.model.Project) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object buildDirectory_ = "";
    /**
     * <code>optional string buildDirectory = 1;</code>
     */
    public java.lang.String getBuildDirectory() {
      java.lang.Object ref = buildDirectory_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buildDirectory_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string buildDirectory = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBuildDirectoryBytes() {
      java.lang.Object ref = buildDirectory_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buildDirectory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string buildDirectory = 1;</code>
     */
    public Builder setBuildDirectory(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      buildDirectory_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string buildDirectory = 1;</code>
     */
    public Builder clearBuildDirectory() {
      
      buildDirectory_ = getDefaultInstance().getBuildDirectory();
      onChanged();
      return this;
    }
    /**
     * <code>optional string buildDirectory = 1;</code>
     */
    public Builder setBuildDirectoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      buildDirectory_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sourceDirectory_ = "";
    /**
     * <code>optional string sourceDirectory = 3;</code>
     */
    public java.lang.String getSourceDirectory() {
      java.lang.Object ref = sourceDirectory_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceDirectory_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sourceDirectory = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSourceDirectoryBytes() {
      java.lang.Object ref = sourceDirectory_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceDirectory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sourceDirectory = 3;</code>
     */
    public Builder setSourceDirectory(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceDirectory_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sourceDirectory = 3;</code>
     */
    public Builder clearSourceDirectory() {
      
      sourceDirectory_ = getDefaultInstance().getSourceDirectory();
      onChanged();
      return this;
    }
    /**
     * <code>optional string sourceDirectory = 3;</code>
     */
    public Builder setSourceDirectoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceDirectory_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.jomofisher.cmakeserver.model.Target> targets_ =
      java.util.Collections.emptyList();
    private void ensureTargetsIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        targets_ = new java.util.ArrayList<com.jomofisher.cmakeserver.model.Target>(targets_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.jomofisher.cmakeserver.model.Target, com.jomofisher.cmakeserver.model.Target.Builder, com.jomofisher.cmakeserver.model.TargetOrBuilder> targetsBuilder_;

    /**
     * <code>repeated .Target targets = 4;</code>
     */
    public java.util.List<com.jomofisher.cmakeserver.model.Target> getTargetsList() {
      if (targetsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(targets_);
      } else {
        return targetsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Target targets = 4;</code>
     */
    public int getTargetsCount() {
      if (targetsBuilder_ == null) {
        return targets_.size();
      } else {
        return targetsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Target targets = 4;</code>
     */
    public com.jomofisher.cmakeserver.model.Target getTargets(int index) {
      if (targetsBuilder_ == null) {
        return targets_.get(index);
      } else {
        return targetsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Target targets = 4;</code>
     */
    public Builder setTargets(
        int index, com.jomofisher.cmakeserver.model.Target value) {
      if (targetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTargetsIsMutable();
        targets_.set(index, value);
        onChanged();
      } else {
        targetsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Target targets = 4;</code>
     */
    public Builder setTargets(
        int index, com.jomofisher.cmakeserver.model.Target.Builder builderForValue) {
      if (targetsBuilder_ == null) {
        ensureTargetsIsMutable();
        targets_.set(index, builderForValue.build());
        onChanged();
      } else {
        targetsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Target targets = 4;</code>
     */
    public Builder addTargets(com.jomofisher.cmakeserver.model.Target value) {
      if (targetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTargetsIsMutable();
        targets_.add(value);
        onChanged();
      } else {
        targetsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Target targets = 4;</code>
     */
    public Builder addTargets(
        int index, com.jomofisher.cmakeserver.model.Target value) {
      if (targetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTargetsIsMutable();
        targets_.add(index, value);
        onChanged();
      } else {
        targetsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Target targets = 4;</code>
     */
    public Builder addTargets(
        com.jomofisher.cmakeserver.model.Target.Builder builderForValue) {
      if (targetsBuilder_ == null) {
        ensureTargetsIsMutable();
        targets_.add(builderForValue.build());
        onChanged();
      } else {
        targetsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Target targets = 4;</code>
     */
    public Builder addTargets(
        int index, com.jomofisher.cmakeserver.model.Target.Builder builderForValue) {
      if (targetsBuilder_ == null) {
        ensureTargetsIsMutable();
        targets_.add(index, builderForValue.build());
        onChanged();
      } else {
        targetsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Target targets = 4;</code>
     */
    public Builder addAllTargets(
        java.lang.Iterable<? extends com.jomofisher.cmakeserver.model.Target> values) {
      if (targetsBuilder_ == null) {
        ensureTargetsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, targets_);
        onChanged();
      } else {
        targetsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Target targets = 4;</code>
     */
    public Builder clearTargets() {
      if (targetsBuilder_ == null) {
        targets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        targetsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Target targets = 4;</code>
     */
    public Builder removeTargets(int index) {
      if (targetsBuilder_ == null) {
        ensureTargetsIsMutable();
        targets_.remove(index);
        onChanged();
      } else {
        targetsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Target targets = 4;</code>
     */
    public com.jomofisher.cmakeserver.model.Target.Builder getTargetsBuilder(
        int index) {
      return getTargetsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Target targets = 4;</code>
     */
    public com.jomofisher.cmakeserver.model.TargetOrBuilder getTargetsOrBuilder(
        int index) {
      if (targetsBuilder_ == null) {
        return targets_.get(index);  } else {
        return targetsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Target targets = 4;</code>
     */
    public java.util.List<? extends com.jomofisher.cmakeserver.model.TargetOrBuilder> 
         getTargetsOrBuilderList() {
      if (targetsBuilder_ != null) {
        return targetsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(targets_);
      }
    }
    /**
     * <code>repeated .Target targets = 4;</code>
     */
    public com.jomofisher.cmakeserver.model.Target.Builder addTargetsBuilder() {
      return getTargetsFieldBuilder().addBuilder(
          com.jomofisher.cmakeserver.model.Target.getDefaultInstance());
    }
    /**
     * <code>repeated .Target targets = 4;</code>
     */
    public com.jomofisher.cmakeserver.model.Target.Builder addTargetsBuilder(
        int index) {
      return getTargetsFieldBuilder().addBuilder(
          index, com.jomofisher.cmakeserver.model.Target.getDefaultInstance());
    }
    /**
     * <code>repeated .Target targets = 4;</code>
     */
    public java.util.List<com.jomofisher.cmakeserver.model.Target.Builder> 
         getTargetsBuilderList() {
      return getTargetsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.jomofisher.cmakeserver.model.Target, com.jomofisher.cmakeserver.model.Target.Builder, com.jomofisher.cmakeserver.model.TargetOrBuilder> 
        getTargetsFieldBuilder() {
      if (targetsBuilder_ == null) {
        targetsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.jomofisher.cmakeserver.model.Target, com.jomofisher.cmakeserver.model.Target.Builder, com.jomofisher.cmakeserver.model.TargetOrBuilder>(
                targets_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        targets_ = null;
      }
      return targetsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:Project)
  }

  // @@protoc_insertion_point(class_scope:Project)
  private static final com.jomofisher.cmakeserver.model.Project DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.jomofisher.cmakeserver.model.Project();
  }

  public static com.jomofisher.cmakeserver.model.Project getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Project>
      PARSER = new com.google.protobuf.AbstractParser<Project>() {
    public Project parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Project(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Project> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Project> getParserForType() {
    return PARSER;
  }

  public com.jomofisher.cmakeserver.model.Project getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

