// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.1.0.proto

package com.jomofisher.cmakeserver.model;

public interface ProjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Project)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string buildDirectory = 1;</code>
   */
  java.lang.String getBuildDirectory();
  /**
   * <code>optional string buildDirectory = 1;</code>
   */
  com.google.protobuf.ByteString
      getBuildDirectoryBytes();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string sourceDirectory = 3;</code>
   */
  java.lang.String getSourceDirectory();
  /**
   * <code>optional string sourceDirectory = 3;</code>
   */
  com.google.protobuf.ByteString
      getSourceDirectoryBytes();

  /**
   * <code>repeated .Target targets = 4;</code>
   */
  java.util.List<com.jomofisher.cmakeserver.model.Target> 
      getTargetsList();
  /**
   * <code>repeated .Target targets = 4;</code>
   */
  com.jomofisher.cmakeserver.model.Target getTargets(int index);
  /**
   * <code>repeated .Target targets = 4;</code>
   */
  int getTargetsCount();
  /**
   * <code>repeated .Target targets = 4;</code>
   */
  java.util.List<? extends com.jomofisher.cmakeserver.model.TargetOrBuilder> 
      getTargetsOrBuilderList();
  /**
   * <code>repeated .Target targets = 4;</code>
   */
  com.jomofisher.cmakeserver.model.TargetOrBuilder getTargetsOrBuilder(
      int index);
}
