// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.1.0.proto

package com.jomofisher.cmakeserver.model;

public interface ProtocolVersionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtocolVersion)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool isExperimental = 1;</code>
   */
  boolean getIsExperimental();

  /**
   * <code>optional int32 major = 2;</code>
   */
  int getMajor();

  /**
   * <code>optional int32 minor = 3;</code>
   */
  int getMinor();
}
