// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.1.0.proto

package com.jomofisher.cmakeserver.model;

public interface TargetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Target)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string artifacts = 1;</code>
   */
  java.util.List<java.lang.String>
      getArtifactsList();
  /**
   * <code>repeated string artifacts = 1;</code>
   */
  int getArtifactsCount();
  /**
   * <code>repeated string artifacts = 1;</code>
   */
  java.lang.String getArtifacts(int index);
  /**
   * <code>repeated string artifacts = 1;</code>
   */
  com.google.protobuf.ByteString
      getArtifactsBytes(int index);

  /**
   * <code>optional string buildDirectory = 2;</code>
   */
  java.lang.String getBuildDirectory();
  /**
   * <code>optional string buildDirectory = 2;</code>
   */
  com.google.protobuf.ByteString
      getBuildDirectoryBytes();

  /**
   * <code>repeated .FileGroup fileGroups = 3;</code>
   */
  java.util.List<com.jomofisher.cmakeserver.model.FileGroup> 
      getFileGroupsList();
  /**
   * <code>repeated .FileGroup fileGroups = 3;</code>
   */
  com.jomofisher.cmakeserver.model.FileGroup getFileGroups(int index);
  /**
   * <code>repeated .FileGroup fileGroups = 3;</code>
   */
  int getFileGroupsCount();
  /**
   * <code>repeated .FileGroup fileGroups = 3;</code>
   */
  java.util.List<? extends com.jomofisher.cmakeserver.model.FileGroupOrBuilder> 
      getFileGroupsOrBuilderList();
  /**
   * <code>repeated .FileGroup fileGroups = 3;</code>
   */
  com.jomofisher.cmakeserver.model.FileGroupOrBuilder getFileGroupsOrBuilder(
      int index);

  /**
   * <code>optional string fullName = 4;</code>
   */
  java.lang.String getFullName();
  /**
   * <code>optional string fullName = 4;</code>
   */
  com.google.protobuf.ByteString
      getFullNameBytes();

  /**
   * <code>optional string linkLibraries = 5;</code>
   */
  java.lang.String getLinkLibraries();
  /**
   * <code>optional string linkLibraries = 5;</code>
   */
  com.google.protobuf.ByteString
      getLinkLibrariesBytes();

  /**
   * <code>optional string linkerLanguage = 6;</code>
   */
  java.lang.String getLinkerLanguage();
  /**
   * <code>optional string linkerLanguage = 6;</code>
   */
  com.google.protobuf.ByteString
      getLinkerLanguageBytes();

  /**
   * <code>optional string name = 7;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 7;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string sourceDirectory = 8;</code>
   */
  java.lang.String getSourceDirectory();
  /**
   * <code>optional string sourceDirectory = 8;</code>
   */
  com.google.protobuf.ByteString
      getSourceDirectoryBytes();

  /**
   * <code>optional string type = 9;</code>
   */
  java.lang.String getType();
  /**
   * <code>optional string type = 9;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>optional string linkFlags = 10;</code>
   */
  java.lang.String getLinkFlags();
  /**
   * <code>optional string linkFlags = 10;</code>
   */
  com.google.protobuf.ByteString
      getLinkFlagsBytes();

  /**
   * <code>optional string sysroot = 11;</code>
   */
  java.lang.String getSysroot();
  /**
   * <code>optional string sysroot = 11;</code>
   */
  com.google.protobuf.ByteString
      getSysrootBytes();
}
